### ISSUE TITLE
colabfold_batch occurs AttributeError

### ISSUE THREAD

**Issue by LunaJang** [sokrypton/ColabFold#108]
I run colabfold_batch, but seems that it tries to load something not exist from TensorFlow

```
$ colabfold_batch train_seqs.fasta train_seqs_structure
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs, please host your own API and pass it to `--host-url`
f115d2822e32f943fab96db219a0f0ca3729b799
2021-11-29 18:15:35,184 Running colabfold 1.2.0 (f115d2822e32f943fab96db219a0f0ca3729b799)
2021-11-29 18:15:35,187 Found 5 citations for tools or databases
2021-11-29 18:15:39,671 Query 1/1519: _58 (length 73)
2021-11-29 18:15:40,056 Running model_3
Traceback (most recent call last):
  File "/home/.../bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/.../lib/python3.8/site-packages/colabfold/batch.py", line 1209, in main
    run(
  File "/home/.../lib/python3.8/site-packages/colabfold/batch.py", line 998, in run
    outs, model_rank = predict_structure(
  File "/home/.../lib/python3.8/site-packages/colabfold/batch.py", line 180, in predict_structure
    processed_feature_dict = model_runner.process_features(
  File "/home/.../lib/python3.8/site-packages/alphafold/model/model.py", line 132, in process_features
    return features.np_example_to_features(
  File "/home/.../lib/python3.8/site-packages/alphafold/model/features.py", line 92, in np_example_to_features
    tf.compat.v1.set_random_seed(random_seed)
  File "/home/.../lib/python3.8/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.compat.v1.compat' has no attribute 'v1'
```

below are the result of 'pip list' from my conda env.

> tensorboard                  2.7.0
> tensorboard-data-server      0.6.1
> tensorboard-plugin-wit       1.8.0
> tensorflow-cpu               2.7.0
> tensorflow-estimator         2.7.0
> tensorflow-io-gcs-filesystem 0.22.0
> tensorflow-probability       0.8.0

Have I installed the wrong version of TF?

**Comment by konstin** [comment]
Solved by recreating the conda environment
