### ISSUE TITLE
ColabFold: AlphaFold2 using MMseqs2

### ISSUE THREAD

**Issue by mauricirl** [sokrypton/ColabFold#126]
Hi, I got  this error both with GPU or TPU for a protein complex
prediction:

2021-12-14 19:08:28,618 Could not generate input features t54t2_897ab: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1042, in run
    model_type,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 767, in generate_input_feature
    input_feature = process_multimer_features(features_for_chain)
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 643, in process_multimer_features
    chain_features, chain_id
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/pipeline_multimer.py", line 83, in convert_monomer_features
    feature = np.asarray(feature[0], dtype=feature.dtype)
IndexError: index 0 is out of bounds for axis 0 with size 0
2021-12-14 19:08:28,625 Done

More info:
use_amber: y
use_templates: n
save_to_google_drive: n
msa_mode: MMseqs2 (UniRef+Environmental)
model_type: auto
pair_mode: unpaired+paired
num_recycles: 3

Any help is highly appreciated.
Regards,

-- Maurizio

**Comment by martin-steinegger** [comment]
Can you please share your input sequence?

**Comment by martin-steinegger** [comment]
Thank you for the sequence. I ran it without any issue. I guess you got an instance with not enough RAM.
Did you try a factory reset? 
Here is the prediction just in case: https://www.dropbox.com/t/amdw3G2UGHaKI534

**Comment by mauricirl** [comment]
Thank you so much for your support. I will try your suggestion.
