### ISSUE TITLE
Error in specific run

### ISSUE THREAD

**Issue by Meravbraitbard** [sokrypton/ColabFold#127]
## I tried to run this sequence in the colab: ILKFPSQSITQTLINKYLSTITETNSILPILKPKRLLPIVEQLFPSNTINKPNSKDFETIFQVFSVTNDQLLNLGFITLCLLILFESLNSTVLIPLRDDEHLQLFNVLFNYLPLLKSNLTTLRFEIEKRSMCNIETLRFISLWKYYQFVMDTSSSSSFVIDYDEDMHMACLLSLNHETQNQSHILTWNFIFKNYCWRHLFLGQLPLLMSEPFTNSTPIIDPLLNNDFELIDFEVNLMKYLQSKDQQLSIDKIIQLIKLLKNKNIEVSQGCLTTPSIINNIMDSLIYRNSMLYLNFYLLLQFETLKNYAKFNEILEDFLELSRETLFFVFSNLANIKFAGHEFTFINKSIVVLQTLVLMLLALYQRSFDSSKRTNDANEISEQTDIHSNNDNSKRIKNKNVIHLIINKIAMLLSDYTKNCKKQNKLIENLIIKIKTISKYIKN:YMEVCKVNFPPKAIIIETLNSESLNNLNIEEFLPIFDKTLLLEFVHNSFPNGDTCPSFSTVDLPLSQLTKLGELTVLLLLLNDSMTLFNKQAINNHVSALMNNLRLIRSQITLINLEYYDQETIKFIAITKFYESLYMHDDHKSSLDEDLSCLLSFQIKDFKLFHFLKKMYYSRHSLLGQSSFMVPAAENLSPIPASIDTNDIPLIANDLKLLETQAKLINILQGVPFYLPVNLTKIESLLETLTMGVSNTVDLYFHDNEVRKEWKDTLNFINTIVYTNFFLFVQNESSLSMAVQHSSNNNKTSNSERCAKDLMKIISNMHIFYSITFNFIFPIKSIKSFSSGNNRFHSNGKEFLFANHFIEILQNFIAITFAIFQRCEVILYDEFYKNLSNEEINVQLLLIHDKILEILKKIEIIVSFLRDEMNSNGSFKSIKGFNKVLNLIKYML
and I expected to get structure of a complex.

## Current Behavior
Every time I'm getting another error. the latest error is :
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1042, in run
    model_type,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 767, in generate_input_feature
    input_feature = process_multimer_features(features_for_chain)
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 643, in process_multimer_features
    chain_features, chain_id
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/pipeline_multimer.py", line 88, in convert_monomer_features
    feature = np.argmax(feature, axis=-1).astype(np.int32)
  File "<__array_function__ internals>", line 6, in argmax
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 1188, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
2021-12-14 10:16:28,729 Done

## Context
this is a coplex that we know that work together and we want to see how it's look. 

## Your Environment
* Colab version: AlphaFold2.ipynb

**Comment by martin-steinegger** [comment]
I could just run it without an error. Did you try a factory reset?
Here is the zip: https://www.dropbox.com/t/Lb76vfDt2bCHcHbf

**Comment by Meravbraitbard** [comment]
Thanks for the zip file, but,I tried now the factory reset and still getting the same error. when I'm trying another sequences they are working, and I want to try to increase the recycles. Do you have another idea why this is happen?

**Comment by martin-steinegger** [comment]
Yes, I think the node you get from google has too little RAM. You could consider updating to Google Pro, which increases your chance to get a node with more memory and a better GPU. Alternative you could run it on a local compute using our `pip` installable version. ColabFold using AlphaFold2 can also run on CPU only systems its just very slow.
