### ISSUE TITLE
Run Prediction halted

### ISSUE THREAD

**Issue by nmrworker** [sokrypton/ColabFold#129]
## Current Behavior
Using the latest Alphafold2.ipynb from https://github.com/sokrypton/ColabFold, I kept got this error at the beginning of "Run Prediction" stage today and the calculation was stopped:
========
Downloading alphafold2 weights to .: 100%|██████████| 3.82G/3.82G [00:30<00:00, 133MB/s] 
2021-12-21 21:03:55,809 Running colabfold 1.2.0 (fc00f951cef535d3a643bf432f965b4eeba71b0e)
2021-12-21 21:03:55,812 Found 6 citations for tools or databases
2021-12-21 21:04:07,801 Query 1/1: test14a_3171d (length 463)
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]
2021-12-21 21:04:08,422 Server didn't reply with json: Key: 'ParamsDisplayV1.Display.Name' Error:Field validation for 'Name' failed on the 'required' tag

2021-12-21 21:04:08,428 Could not get MSA/templates for test14a_3171d: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1029, in run host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 586, in get_msa_and_templates host_url=host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/colabfold.py", line 149, in run_mmseqs2  raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2021-12-21 21:04:08,433 Done
========

## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 
APGQKECDNALRELETVRELLENPVQPINDMSYFGCLDSVMENSKVLGEAMTGISQNAKNGNLPEFGDAISTASKALCGFTEAAAQAAYLVGVSDPNSQAGQQGLVEPTQFARANQAIQMACQSLGEPGCTQAQVLSAATIVAKHTSALCNSCRLASARTTNPTAKRQFVQSAKEVANSTANLVKTIKALDGAFTEENRAQCRAATAPLLEAVDNLSAFASNPEFSSIPAQISPEGRAAMEPIVISAKTMLESAGGLIQTARALAVNPRDPPSWSVLAGHSRTVSDSIKKLITSMRDKAPGQL:MDDLDALLADLESTTSHISKRPVFLSEETPYSYPTGNHTYQEIAVPPPVPPPPSSEALNGTILDPLDQWQPSSSRFIHQQPQSSSPVYGSSAKTSSVSNPQDSVGSPCSRVGEEEHVYSFPNKQKSAEPSPTVMSTSLGSNLSELDRLLLELNAVQHNPP

using all default settings for a 1:1 complex

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version: Kubuntu 20.04 LTS

**Comment by jfbazan** [comment]
I've had pretty much the same issue, on both the multimer-capable ColabFold as well as the older Advanced (AF2.0) version, when trying to use MMSeq2. On the former Colab, there's no other option, so the notebook crashes. On the older version, choose JackHmmer and it will run. The DeepMind AF2.1 Colab that uses JackHmmer exclusively appears to work ok, so the problem lies with calling MMSeq2.

SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]2021-12-21 21:27:38,280 Server didn't reply with json: Key: 'ParamsDisplayV1.Display.Name' Error:Field validation for 'Name' failed on the 'required' tag

2021-12-21 21:27:38,285 Could not get MSA/templates for XXXXX_12fd0: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1029, in run
    host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 586, in get_msa_and_templates
    host_url=host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/colabfold.py", line 149, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2021-12-21 21:27:38,289 Done

**Comment by martin-steinegger** [comment]
Our server had an outage. We restarted it. It should work again. Sorry for the inconvenience.

**Comment by jfbazan** [comment]
No worries at all, Martin! Thx to you and Sergey for all your brilliant efforts with the ColabFold initiative, and all the best on the holidays,

Cheers, Fernando

**Comment by martin-steinegger** [comment]
Thank you so much for the kind words @jfbazan. 
ColabFold is team effort. Actually @milot-mirdita fixed the server. :) 
Happy holidays to you too.

**Comment by nmrworker** [comment]
It went through smoothly now. Thanks!

**Comment by susheelbhanu** [comment]
Hi, 

I'm getting a similar issue, but with longer protein sequences, i.e. 10,000 aminoacids or longer. 

```
2023-03-28 14:38:16,358 Could not get MSA/templates for LJNFGEOL_491293: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
```

I've checked the protein sequence seems fine. Attached here for reference.  
[long_protein.faa.txt](https://github.com/sokrypton/ColabFold/files/11096933/long_protein.faa.txt)

Thank you,
Susheel
