### ISSUE TITLE
Error in batch.py?

### ISSUE THREAD

**Issue by barkailab** [sokrypton/ColabFold#167]
Dear Colabfold team,

thanks for sharing this useful tool with the broader public.
I just started using colabfold and  encountered this error:

Traceback (most recent call last):
  File "/home/labs/barkailab/felixj/.conda/envs/colab/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/labs/barkailab/felixj/.conda/envs/colab/lib/python3.7/site-packages/colabfold/batch.py", line 1386, in main
    save_pairwise_representations=args.save_pairwise_representations,
AttributeError: 'Namespace' object has no attribute 'save_pairwise_representations'

looking at the code i think the line 1386 should say:
save_pair_representations=args.save_pair_representations,

is this possible?

Keep up the great work,
Felix

**Comment by milot-mirdita** [comment]
Seems you are right. Would you mind submitting a pull request?

I am bit surprised that the CI hasn't catch this issue.
