### ISSUE TITLE
Failed to establish a new connection error Issue

### ISSUE THREAD

**Issue by gundalav** [sokrypton/ColabFold#171]
Hi there, 

Just recently I am trying [Colabfold web ](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb#scrollTo=G4yBrceuFbf3)and `colabfold_batch` command line. 

The sequence I used is: `PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK`
The error I got are the same as the following:

```
WARNING: found GPU Tesla K80: limited to total length < 1000
Downloading alphafold2 weights to .: 100%|██████████| 3.47G/3.47G [00:51<00:00, 72.3MB/s]
2022-03-04 09:53:35,076 Running colabfold 1.2.0 (662ab2a281df74ceffad0f9674218cd67beb288f)
2022-03-04 09:53:35,081 Found 5 citations for tools or databases
2022-03-04 09:53:41,216 Query 1/1: test_bb939 (length 44)
SUBMIT:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]2022-03-04 09:53:41,517 Could not get MSA/templates for test_bb939: HTTPSConnectionPool(host='a3m.mmseqs.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f291603ed50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f291603ed50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='a3m.mmseqs.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f291603ed50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1057, in run
    host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 603, in get_msa_and_templates
    host_url=host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/colabfold.py", line 140, in run_mmseqs2
    out = submit(seqs_unique, mode, N)
  File "/usr/local/lib/python3.7/dist-packages/colabfold/colabfold.py", line 80, in submit
    res = requests.post(f'{host_url}/{submission_endpoint}', data={'q':query,'mode': mode})
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='a3m.mmseqs.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f291603ed50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-03-04 09:53:41,527 Done
```

Is there a way we can resolve this?

G.V.

**Comment by martin-steinegger** [comment]
We had a power outage in the data center. working on it.

**Comment by martin-steinegger** [comment]
The service should be running again. Please let us know if the problem is resolved on your side. 
We also changed to a more power full server and switched the database from BFD/Mgnify to the larger ColabFoldDb.

**Comment by gundalav** [comment]
> The service should be running again. Please let us know if the problem is resolved on your side.
> We also changed to a more power full server and switched the database from BFD/Mgnify to the larger ColabFoldDb.

Thanks for the quick response. I tested. It's working great now!

G.V.
