### ISSUE TITLE
Using your own PDB as a template

### ISSUE THREAD

**Issue by duhovka** [sokrypton/ColabFold#190]
I am trying to use my own template (single PDB in a cif format) with AF2-multimer (AlphaFold2 notebook in Collab). I get the following error:

2022-03-30 15:56:15,988 Could not get MSA/templates for test_1848a: hit.name did not start with PDBID_chain: crystal_homodimer_D
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1124, in run
    host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 633, in get_msa_and_templates
    query_seqs_unique[index],
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 123, in mk_template
    query_sequence=query_sequence, hits=hhsearch_hits
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/templates.py", line 902, in get_templates
    kalign_binary_path=self._kalign_binary_path)
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/templates.py", line 697, in _process_single_hit
    hit_pdb_code, hit_chain_id = _get_pdb_id_and_chain(hit)
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/templates.py", line 103, in _get_pdb_id_and_chain
    raise ValueError(f'hit.name did not start with PDBID_chain: {hit.name}')
ValueError: hit.name did not start with PDBID_chain: crystal_homodimer_D

when I try to run locally with "--templates --custom-template-path templates/" option I get the following error:
2022-03-30 17:56:57,159 Could not get MSA/templates for Alpha: [Errno 2] No such file or directory: 'hhsearch': 'hhsearch'

Can you please help resolve this?
Thanks!

**Comment by tanmoy7989** [comment]
@duhovka This is a great question! 

@sokrypton I'm trying to do this same exact thing using native (Deepmind's version) AlphaFold, so any insight on how to force the use of custom template pdbs (with an appropriately reduced MSA depth (say ~40-50 sequences) would be great! My intended targets are not de-novo designed proteins, but common structures that'd be in the PDB. The template/(s) I want to enforce would be, say, a different conformation of one that's available in the PDB.

**Comment by ajasja** [comment]
@duhovka @tanmoy7989  I think this issue should help. https://github.com/sokrypton/ColabFold/issues/177
The cif file has to be named as a pdb ID (four letters) and have a chain identifier. It also has to have entries about time and the sequence.
