### ISSUE TITLE
MMseqs2 API is giving errors.

### ISSUE THREAD

**Issue by ExaptedAI** [sokrypton/ColabFold#192]
## Expected Behavior
ColabFold Batch should have run this sequence without any issues.

## Current Behavior
MMseqs2 API is giving errors.

## ColabFold Output (for bugs)
2022-04-02 23:58:26,758 Query 1547/1549: Prokka_00230_Putative_Gly-rich_membrane_protein (length 1851)
SUBMIT:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]
2022-04-02 23:58:27,560 Server didn't reply with json: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
2022-04-02 23:58:27,566 Could not get MSA/templates for Prokka_00230_Putative_Gly-rich_membrane_protein: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1124, in run
    host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 664, in get_msa_and_templates
    host_url=host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/colabfold.py", line 149, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
## Steps to Reproduce (for bugs)
"Factory Reset" in Colab doesn't solve the problem.  In fact, running any sequence gives the result, suggesting that the API may be down.  

## Context
This error occurs not only in the batch mode but the regular AlphaFold2 Advanced as well.

## Your Environment
Colab Pro+
****

**Comment by martin-steinegger** [comment]
We had a 10 minutes planned power outage in our building. The server was down for approx. 10-20 minutes. 
All should be up and running again.

**Comment by ExaptedAI** [comment]
It's all working fine now, @martin-steinegger.  Thank you for the heads-up.
