### ISSUE TITLE
Sequence 0 found templates: []

### ISSUE THREAD

**Issue by ajasja** [sokrypton/ColabFold#201]
## Expected Behavior
Colabfold takes the custom template into account.
(I'm trying to use just part of a custom template.)

## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 

## ColabFold Output (for bugs)
2022-04-12 09:19:04,446 Query 1/1: 8v8_96834 (length 1136)
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:01 remaining: 00:00]
2022-04-12 09:19:06,967 Sequence 0 found templates: []
2022-04-12 09:19:12,537 Could not generate input features 8v8_96834: attempt to get argmax of an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1145, in run
    model_type,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 853, in generate_input_feature
    input_feature = process_multimer_features(features_for_chain)
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 727, in process_multimer_features
    chain_features, chain_id
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/pipeline_multimer.py", line 88, in convert_monomer_features
    feature = np.argmax(feature, axis=-1).astype(np.int32)
  File "<__array_function__ internals>", line 6, in argmax
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 1195, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
2022-04-12 09:19:12,566 Done

## Context
I'm trying to use just part of a custom template.
[n8g2.zip](https://github.com/sokrypton/ColabFold/files/8471618/n8g2.zip) with this sequence (
MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA:MAVEKTNSSSSLAEVIDRILDKGIVIDAWVRVSLVGIELLAIEARIVIASVETYLKYAEAVGLTQSAAVPA
)

![image](https://user-images.githubusercontent.com/19926/162928144-d9f302fe-ed30-4bfc-89eb-54a490a58a63.png)

**Comment by ajasja** [comment]
Hmm, it appears I was missing the _entity_poly_seq. I wish there was a good PDB to mmCIF command line program.

**Comment by martin-steinegger** [comment]
We want to do this automatically but haven’t had time to implement this yet. :/

**Comment by ajasja** [comment]
Yes, I understand, converting PDBs to mmCIF is a bit out of scope.
