### ISSUE TITLE
Multimer-v2 KeyError: 'data'

### ISSUE THREAD

**Issue by tubiana** [sokrypton/ColabFold#205]
Hi all :-) 

I'm trying to use colabfold_batch from a singularity image with the multimer-v2 version.
I used colabfold_search before to get my alignments, and I have now 2 sequences `0.a3m` and `1.a3m` in my msa folder.
I run the command 
```bash
singularity exec --env TF_FORCE_UNIFIED_MEMORY=1,XLA_PYTHON_CLIENT_MEM_FRACTION=4.0,OPENMM_CPU_THREADS=8  \
            -B ${OUTPUT_DIR}:/inout/output -B ${FASTA_DIR}:/inout/fasta -B ${MSA_DIR}:/inout/msas -B ${PRED_DIR}:/inout/predictions \
	        --nv colabfold_std_v100322.sif \
            colabfold_batch --model-type AlphaFold2-multimer-v2 \
            /inout/msas /inout/predictions
```
 and I have the following error 
```
2022-04-15 18:10:00,872 Running colabfold 1.2.0 (5ddfd0bbadbffc5757ee1912107704aec3cd8c04)
2022-04-15 18:10:00,906 Found 5 citations for tools or databases
2022-04-15 18:10:07,700 Query 1/2: 1 (length 129)
2022-04-15 18:10:07,754 Running model_3
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 883, in __getitem__
    field = self._fields[key]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 807, in __getattr__
    return self[attribute]
  File "/opt/conda/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 889, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'data'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/colabfold/batch.py", line 1445, in main
    run(
  File "/opt/conda/lib/python3.8/site-packages/colabfold/batch.py", line 1156, in run
    outs, model_rank = predict_structure(
  File "/opt/conda/lib/python3.8/site-packages/colabfold/batch.py", line 249, in predict_structure
    input_features = batch_input(
  File "/opt/conda/lib/python3.8/site-packages/colabfold/batch.py", line 188, in batch_input
    eval_cfg = model_config.data.eval
  File "/opt/conda/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 809, in __getattr__
    raise AttributeError(e)
AttributeError: "'data'"
```

Unfortunatly https://github.com/sokrypton/ColabFold/issues/174 is not the same and https://github.com/sokrypton/ColabFold/issues/104 is not applicable since I already have the alignment with `colabfold_search`

Could you give me a hint :-) ? Is that my usage that it is wrong ? 

Thank you :-)
Thibault.

**Comment by tubiana** [comment]
I close it because it was resolved by itself... Somehow...
Thank you :)

**Comment by matteoferla** [comment]
I just tripped on this. It is because in my klutzhood I accidentally omitted `--data 👾👾👾` folder.  😵‍💫 
This is the folder that _contains_ the `params` folder of the AF2 models, which in the actual python code this is `data_dir`.
