### ISSUE TITLE
parsing_result.mmcif_object.header['release_date'], '%Y-%m-%d') KeyError: 'release_date'

### ISSUE THREAD

**Issue by mahdikalhori** [sokrypton/ColabFold#217]
## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version:

Hello all!
while using AlphaFold2.ipynb with template structure, upon running I get the following error. It is an error when using template structure.

WARNING: found GPU Tesla K80: limited to total length < 1000
Downloading alphafold2 weights to .: 100%|██████████| 3.82G/3.82G [00:53<00:00, 76.6MB/s]
2022-04-25 10:59:42,777 Running colabfold 1.3.0 (d6b0670552ce3f39e20b69f9e01521ca39562336)
2022-04-25 10:59:42,780 Found 7 citations for tools or databases
2022-04-25 10:59:50,806 Query 1/1: AF_test_open_hASIC1a_69ea9 (length 527)
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:00 remaining: 00:00]
2022-04-25 10:59:59,979 Could not get MSA/templates for AF_test_open_hASIC1a_69ea9: 'release_date'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1140, in run
    host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 637, in get_msa_and_templates
    query_seqs_unique[index],
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 123, in mk_template
    query_sequence=query_sequence, hits=hhsearch_hits
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/templates.py", line 891, in get_templates
    kalign_binary_path=self._kalign_binary_path)
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/templates.py", line 734, in _process_single_hit
    parsing_result.mmcif_object.header['release_date'], '%Y-%m-%d')
KeyError: 'release_date'
2022-04-25 10:59:59,992 Done 

I appreciate your help solving this issue.
Mahdi

**Comment by JinyuanSun** [comment]
Hi, I got this error too. It appears to be alphafold needs the release date of a mmCIF input. You need to append a date record in your template.

**Comment by milot-mirdita** [comment]
ColabFold should now automatically generate this field if its missing.
