### ISSUE TITLE
Relaxation Error Running Locally

### ISSUE THREAD

**Issue by RaymondRuff** [sokrypton/ColabFold#256]
## Expected Behavior
Have functional --amber and --use-gpu-relax implementation. 

## Current Behavior
First model will fold but crash immediately when the relaxation step begins.

## Steps to Reproduce (for bugs)
conda update conda
conda create -n colabfold python=3.7
conda activate colabfold
pip install --upgrade pip
pip install "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold"
conda install cudatoolkit
conda install cudnn
pip install "jax[cuda11_cudnn805]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
conda install -y -c conda-forge -c bioconda kalign2=2.04 hhsuite=3.3.0
conda install -y -c conda-forge openmm=7.5.1 pdbfixer (This does cause a small error that says failed with initial frozen solve but does complete, maybe this is where the problem lies)
colabfold_batch 6CDX.fasta out1/ --num-models 1 --amber --use-gpu-relax

## ColabFold Output (for bugs)
2022-06-27 20:23:01,839 Running colabfold 1.3.0 (2a47c6f1459fbbdb5242cbc62173f9b513813cfa)
Downloading alphafold2 weights to /home/ubuntu/.cache/colabfold: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.47G/3.47G [00:13<00:00, 277MB/s]
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-06-27 20:23:16,563 generated new fontManager
2022-06-27 20:23:18,610 Found 6 citations for tools or databases
2022-06-27 20:23:22,591 Query 1/1: 6CDX (length 36)
COMPLETE: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:01 remaining: 00:00]
2022-06-27 20:23:23,763 Running model_3
2022-06-27 20:23:46,034 model_3 took 19.9s (3 recycles) with pLDDT 74.4 and ptmscore 0.432
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/colabfold/batch.py", line 1724, in main
    run(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/colabfold/batch.py", line 1369, in run
    outs, model_rank = predict_structure(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/colabfold/batch.py", line 441, in predict_structure
    patch_openmm()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/colabfold/batch.py", line 69, in patch_openmm
    from simtk.openmm import app
ModuleNotFoundError: No module named 'simtk'

## Your Environment
cudatoolkit-11.3.1  
cudnn-8.2.1 
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:05:00.0 Off |                  Off |
| 30%   38C    P8    18W / 300W |      1MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

Additionally, I at first thought my openmm install was incorrect, but running python -m simtk.testInstallation reports all differences within tolerance.

**Comment by YoshitakaMo** [comment]
I use the localcolabfold installer, and it didn't reproduce the error with the latest commit of colabfold.

```
$ cat 6cdx.fasta
>6CDX_1
XGCILNGRTDLGTLLFRCRRDSDCPGACICRGNGYCG

$ colabfold_batch 6cdx.fasta out1/ --num-models 1 --amber --use-gpu-relax
2022-07-20 01:58:18,980 Running colabfold 1.3.0 (26de12d3afb5f85d49d0c7db1b9371f034388395)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-07-20 01:58:20,173 Found 6 citations for tools or databases
2022-07-20 01:58:21,639 Query 1/1: 6CDX_1 (length 37)
COMPLETE: 100%|████████████████| 150/150 [elapsed: 00:01 remaining: 00:00]
2022-07-20 01:58:22,781 Running model_3
2022-07-20 01:58:37,940 model_3 took 13.6s (3 recycles) with pLDDT 71.8 and ptmscore 0.409
2022-07-20 01:58:47,105 Relaxation took 7.9s
2022-07-20 01:58:47,105 reranking models by plddt
2022-07-20 01:58:47,585 Done
```

> conda install -y -c conda-forge openmm=7.5.1 pdbfixer (This does cause a small error that says failed with initial frozen solve but does complete, maybe this is where the problem lies)

The GPU relaxation depends on the openmm package. Could you share the error message?

**Comment by RaymondRuff** [comment]
Interestingly when I install using the localcolabfold installer I do not have an error and am able to use --use-gpu-relax. The error only occurs when following the colabfold documentation or the environment.yml I provided above. I will use the localcolabfold installer from now on to avoid the error.

Since you asked though, below is the full error I see when trying to use amber on gpu using the install from the environment.yml.

(colabfold) rruff@pplhpc1gn003:~$ colabfold_batch 6CDX.fasta out1/ --num-models 1 --amber --use-gpu-relax
2022-07-19 10:08:26,699 Running colabfold 1.3.0 (26de12d3afb5f85d49d0c7db1b9371f034388395)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-07-19 10:08:43,808 Found 6 citations for tools or databases
2022-07-19 10:08:48,139 Query 1/5: 6CDX1 (length 36)
2022-07-19 10:08:50,655 Running model_3                                                                                                                                                          | 0/150 [elapsed: 00:00 remaining: ?]
2022-07-19 10:09:25,400 model_3 took 31.4s (3 recycles) with pLDDT 77.5 and ptmscore 0.456
Traceback (most recent call last):
  File "/home/rruff/miniconda3/envs/colabfold/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/rruff/miniconda3/envs/colabfold/lib/python3.7/site-packages/colabfold/batch.py", line 1756, in main
    stop_at_score_below=args.stop_at_score_below,
  File "/home/rruff/miniconda3/envs/colabfold/lib/python3.7/site-packages/colabfold/batch.py", line 1389, in run
    random_seed=random_seed,
  File "/home/rruff/miniconda3/envs/colabfold/lib/python3.7/site-packages/colabfold/batch.py", line 479, in predict_structure
    relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
  File "/home/rruff/miniconda3/envs/colabfold/lib/python3.7/site-packages/alphafold/relax/relax.py", line 66, in process
    use_gpu=self._use_gpu)
  File "/home/rruff/miniconda3/envs/colabfold/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py", line 483, in run_pipeline
    use_gpu=use_gpu)
  File "/home/rruff/miniconda3/envs/colabfold/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py", line 419, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.
