### ISSUE TITLE
cannot access "*.a3m": No such file or directory since 2a47c6f1459fbbdb5242cbc62173f9b513813cfa

### ISSUE THREAD

**Issue by tubiana** [sokrypton/ColabFold#258]
## Expected Behavior
Running colabfold_batch with several A3M alignement files a single folder.

## Current Behavior
with several A3M on a single folder

## Steps to Reproduce (for bugs)
After clean install on a singularity (definition here : https://github.com/tubiana/colabfold_singularity/blob/main/colabfold_receipe.def) 
and commands are here: https://github.com/tubiana/colabfold_singularity/blob/main/run_pred.sh

## ColabFold Output (for bugs)

```bash
-- Doing models --
2022-07-03 22:55:23,807 Running colabfold 1.3.0 (2a47c6f1459fbbdb5242cbc62173f9b513813cfa)
Traceback (most recent call last):
  File "/opt/conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/colabfold/batch.py", line 1708, in main
    queries, is_complex = get_queries(args.input, args.sort_queries_by)
  File "/opt/conda/lib/python3.7/site-packages/colabfold/batch.py", line 646, in get_queries
    (seqs, header) = parse_fasta(file.read_text())
  File "/opt/conda/lib/python3.7/site-packages/colabfold/batch.py", line 589, in parse_fasta
    sequences[index] += line
IndexError: list index out of range
ls: cannot access '*.a3m': No such file or directory
```

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit = 2a47c6f1459fbbdb5242cbc62173f9b513813cfa
* run in a singularity image (see receipe here) : https://github.com/tubiana/colabfold_singularity/blob/main/colabfold_receipe.def 
* commands: https://github.com/tubiana/colabfold_singularity/blob/main/run_pred.sh 

Thank you :)

**Comment by tubiana** [comment]
the issue was actually a format error in One of the numerous a3m file... sorry for that...
