### ISSUE TITLE
KeyError: 'release_date' while using PDB70 Templates

### ISSUE THREAD

**Issue by RaymondRuff** [sokrypton/ColabFold#267]
## Expected Behavior
I am trying to predict a structure while using the PDB70 for template search in Google Colab.

## Current Behavior
Enabling templates results in an error but only for a single sequence, in tests with different sequences it is able to complete.
This seems identical to issue #217 which was closed and supposedly fixed so I am unsure what the problem is.

## Steps to Reproduce (for bugs)
Open Google Colab
enter the following sequence: MDERLSLLRSPPPPSARHRAHPPQRPASSGGAHTLVNHGYAEPAAGRELPPDMTVVPGDHLLEPEVADGGGAPPQGGCGGGGCDRYEPLPPSLPAAGEQDCCGERVVINISGLRFETQLKTLCQFPETLLGDPKRRMRYFDPLRNEYFFDRNRPSFDAILYYYQSGGRIRRPVNVPIDIFSEEIRFYQLGEEAMEKFREDEGFLREEERPLPRRDFQRQVWLLFEYPESSGPARGIAIVSVLVILISIVIFCLETLPEFRDEKDYPASTSQDSFEAAGNSTSGSRAGASSFSDPFFVVETLCIIWFSFELLVRFFACPSKATFSRNIMNLIDIVAIIPYFITLGTELAERQGNGQQAMSLAILRVIRLVRVFRIFKLSRHSKGLQILGQTLKASMRELGLLIFFLFIGVILFSSAVYFAEADDPTSGFSSIPDAFWWAVVTMTTVGYGDMHPVTIGGKIVGSLCAIAGVLTIALPVPVIVSNFNYFYHRETEGEEQSQYMHVGSCQHLSSSAEELRKARSNSTLSKSEYMVIEEGGMNHSAFPQTPFKTGNSTATCTTNNNPNSCVNIKKIFTDV
Under 'template_mode' select PDB70
Runtime -> Run All

## ColabFold Output (for bugs)
Downloading alphafold2 weights to .: 100%|██████████| 3.47G/3.47G [00:19<00:00, 187MB/s]
2022-07-13 21:02:15,613 Found 7 citations for tools or databases
2022-07-13 21:02:21,819 Query 1/1: test_407d2 (length 575)
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:04 remaining: 00:00]
2022-07-13 21:02:57,020 Could not get MSA/templates for test_407d2: 'release_date'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1336, in run
    host_url,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 790, in get_msa_and_templates
    query_seqs_unique[index],
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 168, in mk_template
    query_sequence=query_sequence, hits=hhsearch_hits
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/templates.py", line 891, in get_templates
    kalign_binary_path=self._kalign_binary_path)
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/templates.py", line 734, in _process_single_hit
    parsing_result.mmcif_object.header['release_date'], '%Y-%m-%d')
KeyError: 'release_date'
2022-07-13 21:02:57,036 Done

## Your Environment
Google colab with Tesla P100

**Comment by dxzh0129** [comment]
I'm getting the same error

**Comment by milot-mirdita** [comment]
The issue should be fixed now

**Comment by dxzh0129** [comment]
Yeah it works for me now. Thanks Milot!
