### ISSUE TITLE
Could not find CIFs

### ISSUE THREAD

**Issue by danboshuiyan** [sokrypton/ColabFold#268]
## Expected Behavior
Use ColabFold to predict complex including a target and two ligand, on my local computer
## Current Behavior
There are 600 sequence in the csv files, where every sequence is made by the same way. However, part of the sequences from the file can be predicted by colabfold, while others can not be.
## Steps to Reproduce (for bugs)
colabfold_batch --amber --templates --num-recycle 3  --msa-mode 'MMseqs2 (UniRef+Environmental)' --use-gpu-relax complex1Gtonew_rif1_600-1299.csv complex1Gtonew_rif1_600-1299

## ColabFold Output (for bugs)
2022-07-14 12:59:43,589 Query 486/600: complex1085 (length 315)
2022-07-14 12:59:44,104 Sleeping for 9s. Reason: RATELIMIT
2022-07-14 12:59:53,564 Sleeping for 9s. Reason: RATELIMIT
2022-07-14 13:00:03,028 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:00:09,522 Sleeping for 9s. Reason: RATELIMIT
2022-07-14 13:00:19,046 Sleeping for 9s. Reason: RATELIMIT
2022-07-14 13:00:28,499 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:00:35,038 Sleeping for 8s. Reason: RATELIMIT
2022-07-14 13:00:43,535 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:00:50,167 Sleeping for 7s. Reason: RATELIMIT
2022-07-14 13:00:57,628 Sleeping for 9s. Reason: RATELIMIT
2022-07-14 13:01:07,097 Sleeping for 7s. Reason: RATELIMIT
2022-07-14 13:01:14,573 Sleeping for 10s. Reason: RATELIMIT
2022-07-14 13:01:25,079 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:01:31,547 Sleeping for 8s. Reason: RATELIMIT
2022-07-14 13:01:40,031 Sleeping for 7s. Reason: RATELIMIT
2022-07-14 13:01:47,543 Sleeping for 10s. Reason: RATELIMIT
2022-07-14 13:01:58,001 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:02:04,510 Sleeping for 10s. Reason: RATELIMIT
2022-07-14 13:02:15,019 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:02:21,606 Sleeping for 8s. Reason: RATELIMIT
2022-07-14 13:02:30,113 Sleeping for 10s. Reason: RATELIMIT
2022-07-14 13:02:40,663 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:02:47,251 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:02:53,711 Sleeping for 10s. Reason: RATELIMIT
2022-07-14 13:03:04,291 Sleeping for 6s. Reason: RATELIMIT
2022-07-14 13:03:10,809 Sleeping for 10s. Reason: RATELIMIT
2022-07-14 13:03:21,330 Sleeping for 8s. Reason: RATELIMIT
2022-07-14 13:03:29,864 Sleeping for 9s. Reason: RATELIMIT
2022-07-14 13:03:39,392 Sleeping for 7s. Reason: PENDING
2022-07-14 13:03:46,917 Sleeping for 8s. Reason: RUNNING
2022-07-14 13:03:55,367 Sleeping for 6s. Reason: RUNNING
2022-07-14 13:04:01,936 Sleeping for 10s. Reason: RUNNING
2022-07-14 13:04:19,391 Could not find CIFs in /home/liunan/colabFoldData/new_rif1/complex1Gtonew_rif1_600-1199/complex1085_env/templates_101
2022-07-14 13:04:19,392 Could not get MSA/templates for complex1085: Could not find CIFs in /home/liunan/colabFoldData/new_rif1/complex1Gtonew_rif1_600-1199/complex1085_env/templates_101
Traceback (most recent call last):
  File "/home/liunan/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1248, in run
    host_url,
  File "/home/liunan/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 707, in get_msa_and_templates
    query_seqs_unique[index],
  File "/home/liunan/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 116, in mk_template
    obsolete_pdbs_path=None,
  File "/home/liunan/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/data/templates.py", line 828, in __init__
    raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
ValueError: Could not find CIFs in /home/liunan/colabFoldData/new_rif1/complex1Gtonew_rif1_600-1199/complex1085_env/templates_101

## Your Environment
Linux CUDA11.4 A100

**Comment by danboshuiyan** [comment]
Thanks for any help

**Comment by milot-mirdita** [comment]
Was this run just now? I pushed a fix for either this or a similar issue about 3h ago. Can you check if this is still happening?

**Comment by danboshuiyan** [comment]
> Was this run just now? I pushed a fix for either this or a similar issue about 3h ago. Can you check if this is still happening?

Yes,it just happened seconds before.
After I updated to 1.4.0, the problem seems to be solved.
Thanks for reply and for your work.
