### ISSUE TITLE
ValueError: Cannot reshape a tensor with 1554124 elements to shape [3718,419,1] (1557842 elements) for '{{node reshape_msa}} = Reshape[T=DT_INT32, Tshape=DT_INT32](Const_6, reshape_msa/shape)' with input shapes: [3718,418], [3] and with input tensors computed as partial shapes: input[1] = [3718,419,1].

### ISSUE THREAD

**Issue by melyssacheung** [sokrypton/ColabFold#286]
## Expected Behavior
to produce 5 models given two sequences (homodimer) 

## Current Behavior
2022-08-12 09:35:17,620 Running colabfold 1.3.0 (26de12d3afb5f85d49d0c7db1b9371f034388395)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-08-12 09:35:21,588 Found 8 citations for tools or databases
2022-08-12 09:35:23,953 Query 1/1: T230_3 (length 419)
2022-08-12 09:35:28,120 Sequence 0 found templates: ['1h2i_O', '5jrb_F', '5xs0_M', '5jrb_F', '5xs0_M']
2022-08-12 09:35:28,436 Running model_3
Traceback (most recent call last):
  File "batch_2100.py", line 1761, in <module>
    main()
  File "batch_2100.py", line 1756, in main
    stop_at_score_below=args.stop_at_score_below,
  File "batch_2100.py", line 1389, in run
    random_seed=random_seed,
  File "batch_2100.py", line 342, in predict_structure
    feature_dict, random_seed=random_seed
  File "/piercehome/cheungm/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/model/model.py", line 135, in process_features
    random_seed=random_seed)
  File "/piercehome/cheungm/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/model/features.py", line 94, in np_example_to_features
    np_example=np_example, features=feature_names)
  File "/piercehome/cheungm/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/model/tf/proteins_dataset.py", line 165, in np_to_tensor_dict
    tensor_dict = parse_reshape_logic(tensor_dict, features_metadata)
  File "/piercehome/cheungm/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/model/tf/proteins_dataset.py", line 104, in parse_reshape_logic
    parsed_features[k] = tf.reshape(v, new_shape, name="reshape_%s" % k)
  File "/piercehome/cheungm/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/piercehome/cheungm/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1939, in _create_c_op
    raise ValueError(e.message)
ValueError: Cannot reshape a tensor with 1554124 elements to shape [3718,419,1] (1557842 elements) for '{{node reshape_msa}} = Reshape[T=DT_INT32, Tshape=DT_INT32](Const_6, reshape_msa/shape)' with input shapes: [3718,418], [3] and with input tensors computed as partial shapes: input[1] = [3718,419,1].

## Steps to Reproduce (for bugs)
 python batch_2100.py --amber --templates --num-recycle 3 --use-gpu-relax T230_CT.fasta capri

## ColabFold Output (for bugs)
See error 

## Context
Note: T230_CT.fasta contains 
>T230
PSVEEARYNSCRPNMALGHPQLQQVTSPSRPSHAVIPADQDCSSRSLSSSAVESEATHQRKLRQKQLQQQFRERMEKQQVRVSTPSAEKSEAAPPAPPVTHSTPVTVSEPLLEKDFLAGVTQELIKTLEDNSEKWAVTPDAGDGVVKPSSRADPAQTSDTLALNNQMVTQNRTPHSVCHQKPQAKSGSWDLQTYSADQRTTGNWESHRKSQDMKKRKYDPS:PSVEEARYNSCRPNMALGHPQLQQVTSPSRPSHAVIPADQDCSSRSLSSSAVESEATHQRKLRQKQLQQQFRERMEKQQVRVSTPSAEKSEAAPPAPPVTHSTPVTVSEPLLEKDFLAGVTQELIKTLEDNSEKWAVTPDAGDGVVKPSSRADPAQTSDTLALNNQMVTQNRTPHSVCHQKPQAKSGSWDLQTYSADQRTTGNWESHRKSQDMKKRKYDPS

Capri = output directory 

## Your Environment
1. conda activate colabfold-conda)2. 
2. module unload cuda/10.1
3. module load cuda/11.2. 
4. module unload gcc/7.5. 
5. module load gcc/9.3

**Comment by Geraldene** [comment]
@melyssacheung were you able to resolve this issue?
