### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by gundalav** [sokrypton/ColabFold#330]
Just now I've had a problem with Colabfold both the web version and the command line version. 

This is the message I got from the web server:

<img width="1237" alt="Screen Shot 2022-11-17 at 13 46 38" src="https://user-images.githubusercontent.com/8143832/202358880-47bcbeb5-feb0-40d2-be56-1df2ac0a4955.png">

And this is the error message for the command line:

```
If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-11-17 13:26:16,607 Running colabfold 1.3.0 (26de12d3afb5f85d49d0c7db1b9371f034388395)
2022-11-17 13:26:19,479 Found 6 citations for tools or databases
2022-11-17 13:26:24,052 Query 1/1: 1r1.s5.11a11b.m13.ss1 (length 30)
SUBMIT:   0%|          | 0/150 [elapsed: 02:09 remaining: ?]
2022-11-17 13:28:33,658 Could not get MSA/templates for 1r1.s5.11a11b.m13.ss1: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77dd5c3160>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Traceback (most recent call last):
  File "/home/ubuntu/storage1/conda_envs/colabfold_batch_mm_v2/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ubuntu/storage1/conda_envs/colabfold_batch_mm_v2/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ubuntu/storage1/conda_envs/colabfold_batch_mm_v2/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/storage1/conda_envs/colabfold_batch_mm_v2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ubuntu/storage1/conda_envs/colabfold_batch_mm_v2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntu/storage1/conda_envs/colabfold_batch_mm_v2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/ubuntu/storage1/conda_envs/colabfold_batch_mm_v2/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/ubuntu/storage1/conda_envs/colabfold_batch_mm_v2/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f77dd5c3160>: Failed to establish a new connection: [Errno 110] Connection timed out
```

Please advice how to resolve this.

Sincerely, 
G.V.

**Comment by milot-mirdita** [comment]
Should be back up since a bit ago. We had a small issue with our gateway server.
