### ISSUE TITLE
Colabfold 1.5 error when using --save-recycle (KeyError: 'prev')

### ISSUE THREAD

**Issue by tubiana** [sokrypton/ColabFold#373]
## Expected Behavior
No crash using ` --save-recycles` in colabfold 1.5

## Current Behavior
Crash with colabfold 1.5 when using ` --save-recycles` argument to colabfold_batch (in local

## Steps to Reproduce (for bugs)
Command = 
```bash
colabfold_batch --model-type auto --num-recycle 12 /inout/msas /inout/predictions --save-recycles
```
(the input is a A3M file computed by the MMSEQS server)

My colabfold singularity image was generated a 12h ago. 

## ColabFold Output (for bugs)  
` ` ` bash 
/opt/conda/lib/python3.7/site-packages/Bio/Data/SCOPData.py:21: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  BiopythonDeprecationWarning,
2023-02-05 23:46:31,087 Running colabfold 1.5.0 (68fbdc139905ae769389239994cab9493d57c92b)
2023-02-05 23:46:35,142 Running on GPU
2023-02-05 23:46:35,471 Found 4 citations for tools or databases
2023-02-05 23:46:35,471 Query 1/1: test_dimer (length 191)
2023-02-05 23:46:35,824 Padding length to 191
2023-02-05 23:46:35,829 Setting max_seq=508, max_extra_seq=2048
2023-02-05 23:47:14,150 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=44 pTM=0.203 ipTM=0.068
Traceback (most recent call last):
  File "/opt/conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/colabfold/batch.py", line 1802, in main
    save_recycles=args.save_recycles,
  File "/opt/conda/lib/python3.7/site-packages/colabfold/batch.py", line 1453, in run
    save_recycles=save_recycles,
  File "/opt/conda/lib/python3.7/site-packages/colabfold/batch.py", line 448, in predict_structure
    model_runner.predict(input_features, random_seed=seed, prediction_callback=callback)
  File "/opt/conda/lib/python3.7/site-packages/alphafold/model/model.py", line 217, in predict
    sub_feat["prev"] = result["prev"]
KeyError: 'prev'

` ` ` 

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used: colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold
* If you run it on a local system. Please add the server specifications
  * RTX A6000
  * 256Go RAM
  * 2x INTEL Intel® Xeon(R) Gold 5220R CPU @ 2.20GHz × 96
* Operating system and version: Ubuntu 20.04

**Comment by sokrypton** [comment]
thanks, fixed it! try again.

**Comment by sokrypton** [comment]
oops, just tried to fix again. Should work now 😄

**Comment by tubiana** [comment]
Indeed thank youuu =D
