### ISSUE TITLE
Single sequence .a3m input

### ISSUE THREAD

**Issue by Abhishaike** [sokrypton/ColabFold#410]
How exactly do we provide single-sequence multimer .a3m input to Colabfold? 

for an input of MSGMKKLYEYTVTTLDEFL:EKLKEFILNTSKDKIYKLTITN

This way: 
```
#19,22  1,1
>0
MSGMKKLYEYTVTTLDEFL----------------------
>1
-------------------EKLKEFILNTSKDKIYKLTITN
```

and this way: 
```
#19,22  1,1
>EKLKEFILNTSKDKIYKLTITN MSGMKKLYEYTVTTLDEFL     
MSGMKKLYEYTVTTLDEFLEKLKEFILNTSKDKIYKLTITN
```

Both give this error: 

```
2023-03-11 23:05:06,132 Query 1/1: Sequence_1_2 (length 41)
2023-03-11 23:05:06,133 Could not generate input features Sequence_1_2: MSA 0 must contain at least one sequence.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/colabfold/batch.py", line 1390, in run
    = generate_input_feature(query_seqs_unique, query_seqs_cardinality, unpaired_msa, paired_msa,
  File "/opt/venv/lib/python3.10/site-packages/colabfold/batch.py", line 1005, in generate_input_feature
    feature_dict = build_monomer_feature(
  File "/opt/venv/lib/python3.10/site-packages/colabfold/batch.py", line 861, in build_monomer_feature
    **pipeline.make_msa_features([msa]),
  File "/opt/venv/lib/python3.10/site-packages/alphafold/data/pipeline.py", line 64, in make_msa_features
    raise ValueError(f'MSA {msa_index} must contain at least one sequence.')
ValueError: MSA 0 must contain at least one sequence.
```

**Comment by Abhishaike** [comment]
And to add some more context, I'm running it like this: `colabfold_batch a3m_vol/Sequence_1_2.a3m result -msa-mode single_sequence`

**Comment by Abhishaike** [comment]
Figured it out! It's a mixture of the two 😅, it should look like this: 

```
#19,22  1,1
>EKLKEFILNTSKDKIYKLTITN MSGMKKLYEYTVTTLDEFL     
MSGMKKLYEYTVTTLDEFLEKLKEFILNTSKDKIYKLTITN
>MSGMKKLYEYTVTTLDEFL
MSGMKKLYEYTVTTLDEFL----------------------
>EKLKEFILNTSKDKIYKLTITN
-------------------EKLKEFILNTSKDKIYKLTITN
```

Here's how to create it:

```
seq = 'MSGMKKLYEYTVTTLDEFL:EKLKEFILNTSKDKIYKLTITN'
split_sequence = seq.split(':')
a3m_txt_header = "#" + ','.join(str(len(s)) for s in split_sequence) + '\t' + ','.join(str({s: split_sequence.count(s)}[s]) for s in set(split_sequence)) +  "\n"
a3m_txt_names = '>' + ''.join([s + "\t" for s in set(split_sequence)]) + '\n'
a3m_txt_sequence = ''.join(split_sequence) + '\n'
a3m_txt_dash = []
back_dash = ''
fowards_dash = ''
for i, sequence in enumerate(split_sequence):
    a3m_txt_dash.append('>' + str(sequence) + '\n' + len(''.join(split_sequence[0:i])) * '-' + sequence + len(''.join(split_sequence[i+1:])) * '-' + '\n')
a3m_txt_dash = ''.join(a3m_txt_dash)
a3m_txt_body = a3m_txt_names + a3m_txt_sequence
Path(a3m_volume_path).joinpath(f"{id}.a3m").write_text(a3m_txt_header + a3m_txt_names + a3m_txt_sequence + a3m_txt_dash)
```

**Comment by milot-mirdita** [comment]
Single sequence input is easier in FASTA or csv format.
With those you should not have to go such a roundabout way.
