### ISSUE TITLE
New Lines in A3M custom MSA produces error

### ISSUE THREAD

**Issue by fabgonzal** [sokrypton/ColabFold#426]
## Expected Behavior
A3M files whose entries have new lines should work as MSA input to local colab fold. This is expected because MPI bioinformatics toolkit formatseq preserves FASTA MSA newlines when converting to A3M format
## Current Behavior
While the attached "sml.txt" file runs the attached "broken.txt" file does not with the only difference being that the broken file has newlines in each entry. 
## Steps to Reproduce (for bugs)
colabfold_batch broken.a3m ./test
## ColabFold Output (for bugs)
2023-03-30 11:57:31,613 Running colabfold 1.5.2 (5b3fc193e880cd9599f91cd16fcb1fe69f7759f2)
2023-03-30 11:57:36,324 Running on GPU
2023-03-30 11:57:37,111 Found 4 citations for tools or databases
2023-03-30 11:57:37,112 Query 1/1: broken (length 491)
2023-03-30 11:57:37,113 Could not get MSA/templates for broken: list index out of range
Traceback (most recent call last):
  File "/home/gonzalef/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/batch.py", line 1374, in run
    = unserialize_msa(a3m_lines, query_sequence)
  File "/home/gonzalef/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/batch.py", line 1121, in unserialize_msa
    paired_msa[j] += ">" + header_no_faster_split[j] + "\n"
IndexError: list index out of range
2023-03-30 11:57:37,114 Done
## Context
[broken.txt](https://github.com/sokrypton/ColabFold/files/11113475/broken.txt)
[sml.txt](https://github.com/sokrypton/ColabFold/files/11113471/sml.txt)

**Comment by fabgonzal** [comment]
Also even knowing this I cannot get custom multimer MSAs to work. For example i modified the sml.a3m file and it still works while my file which I believe to be identical in format does not run. Things I have checked: the character counts match, tabs are being used to seperate the lists in the header and the two chains in the first entry, the file uses the same encoding as the file that works. I have attached them and would appreciate any help
[small_test.a3m.txt](https://github.com/sokrypton/ColabFold/file
[sml.a3m.txt](https://github.com/sokrypton/ColabFold/files/11114986/sml.a3m.txt)
s/11114985/small_test.a3m.txt)

**Comment by yakkabio** [comment]
@fabgonzal, for some reason it doesn't seem to like gaps in the first position for any sequences in the MSA. I'm not familiar with a3m format so I'm still trying to figure out how sequences in an MSA without a corresponding amino acid in the first position should be included, but excluding all such sequences works as a stop-gap (for me at least).

**Comment by fabgonzal** [comment]
I finally figured out why my custom multimer MSAs were failing so I thought I would put an update here. As posted elsewhere the format for a multimer is the following. With a,b being sequence lengths of 101 and 102 and c,d being the number of each chain you need. 
#a,b[tab]c,d
\>101[tab]102
paired sequence data
\>101
unpaired sequence data
\>102
unpaired sequence data
There are a lot of ways to go wrong with this so troubleshoot the following. 
1) All sequences must be aligned against \>101[tab]102 in the a3m format. The easy way to do this is to just align against 101 or 102 and when making the final file add the correct number of gaps when concatenating. 
2)All sequences need to be the same "length". Length is in quotes because the actual character counts will differ between sequences because of the a3m format but when converted back to fasta all sequences should have the same number of characters.
3)Obviously the details in the header need to be correct.
4)This is what tripped me up. When including paired sequences the header for each paired sequence must be a tab delimited list of the consituent sequences! So if I am pairing sequence "\>X" with seq "AAA" to sequence "\>Y" with seq "TTT" the result must be
\>X[tab]Y
AAATTT
5)Finally like the issue suggests make sure each sequence is on a single line. This is confusing because HHsuites fasta to a3m converter does not respect this
