### ISSUE TITLE
ColabFold MSA server error in AlphaFold2.ipynb

### ISSUE THREAD

**Issue by bzhousd** [sokrypton/ColabFold#488]
## Expected Behavior
ColabFold MSA server returns results

## Current Behavior

 raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')

## Steps to Reproduce (for bugs)
go to https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb
keep all default values except for 'query_sequence',  which is "AAAAAAAAAAAAAAAAAALLAAA:AAAAAAAAAAAAAAAAAALLAAA:AAAAAAAAAAAAAAAAAALLAAA"

## ColabFold Output (for bugs)
2023-08-11 20:45:03,462 Running on GPU
2023-08-11 20:45:03,466 Found 4 citations for tools or databases
2023-08-11 20:45:03,466 Query 1/1: test_9f888_1 (length 69)
PENDING:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]2023-08-11 20:45:03,876 Sleeping for 6s. Reason: PENDING
ERROR:   0%|          | 0/150 [elapsed: 00:06 remaining: ?]2023-08-11 20:45:10,244 Could not get MSA/templates for test_9f888_1: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1377, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/content/colabfold/batch.py", line 817, in get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/content/colabfold/colabfold.py", line 231, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2023-08-11 20:45:10,245 Done

## Your Environment
N/A

Thanks

**Comment by milot-mirdita** [comment]
Should be back up, might take up to an hour again to update DNS.
