### ISSUE TITLE
Exception: MMseqs2 API is giving errors.

### ISSUE THREAD

**Issue by ctarsi** [sokrypton/ColabFold#507]
## Expected Behavior
Colabfold outputs 5 models.

## Current Behavior
Error in the Run Prediction cell

## Steps to Reproduce (for bugs)
query sequence: "GAGAGAGAGAGAGAGAGAGAGAGAGAGAGA"

## ColabFold Output (for bugs)
2023-10-17 10:51:18,684 Running on GPU
2023-10-17 10:51:18,687 Found 4 citations for tools or databases
2023-10-17 10:51:18,688 Query 1/1: TESTgaga_f5906 (length 30)
PENDING:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]
2023-10-17 10:51:19,292 Sleeping for 9s. Reason: PENDING
ERROR:   0%|          | 0/150 [elapsed: 00:10 remaining: ?]
2023-10-17 10:51:28,948 Could not get MSA/templates for TESTgaga_f5906: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1384, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/content/colabfold/batch.py", line 820, in get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/content/colabfold/colabfold.py", line 238, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2023-10-17 10:51:28,948 Done

## Context
This error persists both using the Colab Notebook and using the local colabfold_batch.
Is the only peptide sequence from a varied and vast list that results in this error. 

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
NOTEBOOK
* ColabFold v1.5.2-patch: AlphaFold2 using MMseqs2
LOCAL
* Operating system and version: Ubuntu 16.04.7 LTS; Cuda compilation tools, release 11.0, V11.0.167

**Comment by milot-mirdita** [comment]
MMseqs2 think you are giving it a nucleotide sequence and then proceeds to fail. I am surprised that this issue was never reported before. I'll see if I can deploy a fix by tomorrow.

**Comment by biodrengen1998** [comment]
Hi! i still seem to be having this, or at least a similar problem, has this been fixed, or could it be related?

fasta:
>1YCQ_12-62
NHISTSDQEKLVQPTPLLLSLLKSAGAQKETFTMKEVIYHLGQYIMAKQLYDEKQQHIVHCSNDPLGELFGVQEFSVKEPRRLYAMISRNLVSANVKESSEDIFGNV:PPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPD

2023-10-26 09:17:15,912 Could not get MSA/templates for 1YCQ_12-62: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/home/mads/alphafold_env/lib/python3.8/site-packages/colabfold/batch.py", line 1449, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/home/mads/alphafold_env/lib/python3.8/site-packages/colabfold/batch.py", line 825, in get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/home/mads/alphafold_env/lib/python3.8/site-packages/colabfold/colabfold.py", line 209, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.

**Comment by milot-mirdita** [comment]
I couldn’t reproduce your issue. The MSA server seems to work fine for your input.

**Comment by yvank89** [comment]
Same issue here, I think:

2024-05-01 07:57:44,502 Running on GPU
2024-05-01 07:57:44,746 Found 5 citations for tools or databases
2024-05-01 07:57:44,746 Query 1/1: K13_E3ubiquitinligase_3d960 (length 62451)
PENDING:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]2024-05-01 07:57:45,446 Sleeping for 9s. Reason: PENDING
RUNNING:   3%|▎         | 9/300 [elapsed: 00:10 remaining: 05:23]2024-05-01 07:57:54,818 Sleeping for 9s. Reason: RUNNING
RUNNING:   6%|▌         | 18/300 [elapsed: 00:19 remaining: 05:01]2024-05-01 07:58:04,164 Sleeping for 7s. Reason: RUNNING
RUNNING:   8%|▊         | 25/300 [elapsed: 00:26 remaining: 04:52]2024-05-01 07:58:11,537 Sleeping for 9s. Reason: RUNNING
RUNNING:  11%|█▏        | 34/300 [elapsed: 00:36 remaining: 04:40]2024-05-01 07:58:20,891 Sleeping for 9s. Reason: RUNNING
RUNNING:  14%|█▍        | 43/300 [elapsed: 00:45 remaining: 04:29]2024-05-01 07:58:30,243 Sleeping for 10s. Reason: RUNNING
RUNNING:  18%|█▊        | 53/300 [elapsed: 00:55 remaining: 04:18]2024-05-01 07:58:40,640 Sleeping for 10s. Reason: RUNNING
RUNNING:  21%|██        | 63/300 [elapsed: 01:06 remaining: 04:06]2024-05-01 07:58:51,007 Sleeping for 7s. Reason: RUNNING
RUNNING:  23%|██▎       | 70/300 [elapsed: 01:13 remaining: 04:00]2024-05-01 07:58:58,373 Sleeping for 10s. Reason: RUNNING
RUNNING:  27%|██▋       | 80/300 [elapsed: 01:23 remaining: 03:49]2024-05-01 07:59:08,726 Sleeping for 10s. Reason: RUNNING
RUNNING:  30%|███       | 90/300 [elapsed: 01:34 remaining: 03:38]2024-05-01 07:59:19,081 Sleeping for 10s. Reason: RUNNING
RUNNING:  33%|███▎      | 100/300 [elapsed: 01:44 remaining: 03:28]2024-05-01 07:59:29,516 Sleeping for 10s. Reason: RUNNING
RUNNING:  37%|███▋      | 110/300 [elapsed: 01:55 remaining: 03:17]2024-05-01 07:59:39,877 Sleeping for 5s. Reason: RUNNING
RUNNING:  38%|███▊      | 115/300 [elapsed: 02:00 remaining: 03:13]2024-05-01 07:59:45,236 Sleeping for 6s. Reason: RUNNING
RUNNING:  40%|████      | 121/300 [elapsed: 02:06 remaining: 03:08]2024-05-01 07:59:51,633 Sleeping for 7s. Reason: RUNNING
RUNNING:  43%|████▎     | 128/300 [elapsed: 02:14 remaining: 03:00]2024-05-01 07:59:58,998 Sleeping for 8s. Reason: RUNNING
RUNNING:  45%|████▌     | 136/300 [elapsed: 02:22 remaining: 02:52]2024-05-01 08:00:07,388 Sleeping for 7s. Reason: RUNNING
RUNNING:  48%|████▊     | 143/300 [elapsed: 02:29 remaining: 02:45]2024-05-01 08:00:14,771 Sleeping for 5s. Reason: RUNNING
RUNNING:  49%|████▉     | 148/300 [elapsed: 02:35 remaining: 02:40]2024-05-01 08:00:20,115 Sleeping for 8s. Reason: RUNNING
RUNNING:  52%|█████▏    | 156/300 [elapsed: 02:43 remaining: 02:31]2024-05-01 08:00:28,486 Sleeping for 10s. Reason: RUNNING
RUNNING:  55%|█████▌    | 166/300 [elapsed: 02:54 remaining: 02:20]2024-05-01 08:00:38,846 Sleeping for 6s. Reason: RUNNING
RUNNING:  57%|█████▋    | 172/300 [elapsed: 03:00 remaining: 02:14]2024-05-01 08:00:45,194 Sleeping for 9s. Reason: RUNNING
RUNNING:  60%|██████    | 181/300 [elapsed: 03:09 remaining: 02:04]2024-05-01 08:00:54,536 Sleeping for 9s. Reason: RUNNING
RUNNING:  63%|██████▎   | 190/300 [elapsed: 03:19 remaining: 01:54]2024-05-01 08:01:03,882 Sleeping for 7s. Reason: RUNNING
RUNNING:  66%|██████▌   | 197/300 [elapsed: 03:26 remaining: 01:47]2024-05-01 08:01:11,275 Sleeping for 7s. Reason: RUNNING
RUNNING:  68%|██████▊   | 204/300 [elapsed: 03:33 remaining: 01:40]2024-05-01 08:01:18,629 Sleeping for 10s. Reason: RUNNING
RUNNING:  71%|███████▏  | 214/300 [elapsed: 03:44 remaining: 01:29]2024-05-01 08:01:28,997 Sleeping for 9s. Reason: RUNNING
RUNNING:  74%|███████▍  | 223/300 [elapsed: 03:53 remaining: 01:20]2024-05-01 08:01:38,345 Sleeping for 6s. Reason: RUNNING
RUNNING:  76%|███████▋  | 229/300 [elapsed: 03:59 remaining: 01:14]2024-05-01 08:01:44,740 Sleeping for 6s. Reason: RUNNING
RUNNING:  78%|███████▊  | 235/300 [elapsed: 04:06 remaining: 01:08]2024-05-01 08:01:51,101 Sleeping for 5s. Reason: RUNNING
RUNNING:  80%|████████  | 240/300 [elapsed: 04:11 remaining: 01:03]2024-05-01 08:01:56,520 Sleeping for 6s. Reason: RUNNING
RUNNING:  82%|████████▏ | 246/300 [elapsed: 04:18 remaining: 00:57]2024-05-01 08:02:02,882 Sleeping for 7s. Reason: RUNNING
RUNNING:  84%|████████▍ | 253/300 [elapsed: 04:25 remaining: 00:49]2024-05-01 08:02:10,264 Sleeping for 5s. Reason: RUNNING
ERROR:  84%|████████▍ | 253/300 [elapsed: 04:30 remaining: 00:50]2024-05-01 08:02:15,615 Could not get MSA/templates for K13_E3ubiquitinligase_3d960: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1463, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/content/colabfold/batch.py", line 824, in get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/content/colabfold/colabfold.py", line 238, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2024-05-01 08:02:15,622 Done

0
