### ISSUE TITLE
Hi I'm trying use <colabfold_search --mmseqs> generate MSA, but it not ran as I expectally, did I missed something? A lot thanks~

### ISSUE THREAD

**Issue by AlvinLeopold** [sokrypton/ColabFold#513]
## Expected Behavior
I thought it will generate a "msas" dictionary, and it contained all a3m files.

## Current Behavior
srun colabfold_search --mmseqs /public/home/xxx/ras_scan/rasras.fasta --db1 uniref30_2302 --db2 pdb100_foldseek_230517 /public/home/xxx/MSA /public/home/xxxMSA/pdb100 /public/home/xxx/ras_scan/msas --threads 36 --use-templates 1

## ColabFold Output (for bugs)
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 1863, in _execute_child
    with Popen(*popenargs, **kwargs) as p:
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 971, in __init__
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/public/home/xxx/ras_scan/rasras.fasta')
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/public/home/xxx/ras_scan/rasras.fasta')
    raise child_exception_type(errno_num, err_msg, err_filename)
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 1863, in _execute_child
PermissionError: [Errno 13] Permission denied: PosixPath('/public/home/xxx/ras_scan/rasras.fasta')
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/public/home/xxx/ras_scan/rasras.fasta')
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/public/home/xxx/ras_scan/rasras.fasta')
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/public/home/xxx/ras_scan/rasras.fasta')
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/public/home/xxx/ras_scan/rasras.fasta')

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
I'm using HPC with intel-E5 and 180Gb RAM

#!/bin/bash
#SBATCH --job-name=RSan32
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --mem=150G

source /public/software/profile.d/.bashrc
conda activate MMseq2
export PATH="/public/home/xxxx/localcolabfold/colabfold-conda/bin:$PATH"

**Comment by milot-mirdita** [comment]
You have to pass the path to the MMseqs2 binary for the `--mmseqs` parameter.

**Comment by AlvinLeopold** [comment]
Thanks~
I've tried it and it exactly run and generate the <msas> dictionary, but I still cannot get the .a3m file. I check the log, and it maybe related to the database. So I rebuild the database

used:

#!/bin/bash
#SBATCH --job-name=test_vasp
#SBATCH --nodes=1
#SBATCH --mem=150G
#SBATCH --ntasks-per-node=36
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

source /public/software/profile.d/.bashrc
echo Conda intialized
conda activate MMseq2
cd /public/home/xxx/MSA
mmseqs tsv2exprofiledb uniref30_2302 uniref30_2302_db

It tooks almost 4h30min, it finished, I can find a lot of db files in db dectionary, but the error log also write some information

Can't locate local/lib.pm in @INC (you may need to install the local::lib module) (@INC contains: /public/home/xxx/.conda/envs/MMseq2/lib/perl5/5.32/site_perl /public/home/xxx/.conda/envs/MMseq2/lib/perl5/site_perl /public/home/xxx/.conda/envs/MMseq2/lib/perl5/5.32/vendor_perl /public/home/xxx/.conda/envs/MMseq2/lib/perl5/vendor_perl /public/home/xxx/.conda/envs/MMseq2/lib/perl5/5.32/core_perl /public/home/xxx/.conda/envs/MMseq2/lib/perl5/core_perl .).
BEGIN failed--compilation aborted.

Now I'm confuse that whether the database were set up properly.

Sincere thaks again~

**Comment by AlvinLeopold** [comment]
After rebuilding the database, I think the MSA now works, but my compute nodes only have a maximum of 563Gb of RAM. I just looked up other issues and found that 768Gb is needed to run the search efficiently. It's frustrating, and I'm now wondering if 563Gb is not available at all or if it's still available with a speed penalty

**Comment by AlvinLeopold** [comment]
Hi there:
I reran colabfold_search when I confirmed that my database was getting all <ready>, but there still seems to be some errors.

`#!/bin/bash
#SBATCH --job-name=RSanMSA
#SBATCH -N 1
#SBATCH --ntasks-per-node=36
#SBATCH --partition=supersmp
#SBATCH --mem=480G
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

module purge
module load /public/software/compiler/gnu/7.2.0
module use /public/home/xxx

source /public/software/profile.d/.bashrc
export PATH="/public/home/xxx/localcolabfold/colabfold-conda/bin:$PATH"
mkdir /public/home/xxx/ras_scan/msas
chmod u+w /public/home/xxx/ras_scan/msas

srun colabfold_search \
--db-load-mode 0 \
--mmseqs mmseqs \
--use-env 1 \
--use-templates 1 \
--threads 36 \
/public/home/xxx/ras_scan/rasras.fasta /public/home/xxx/shared_db/misc/uniref_30 /public/home/xxx/ras_scan/msas
`

and error was `Traceback (most recent call last):
  File "/public/home/xxx/localcolabfold/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 427, in main
    mmseqs_search_monomer(
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 66, in mmseqs_search_monomer
    raise FileNotFoundError(f"Database {db} does not exist")
FileNotFoundError: Database . does not exist
/public/home/xxx/ras_scan/msas/qdb.index.0: No such file or directory
Traceback (most recent call last):
  File "/public/home/xxx/localcolabfold/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 410, in main
    run_mmseqs(
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 23, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('mmseqs'), 'createdb', PosixPath('/public/home/xxx/ras_scan/msas/query.fas'), PosixPath('/public/home/xxx/ras_scan/msas/qdb'), '--shuffle', '0']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/public/home/xxx/localcolabfold/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 410, in main
    run_mmseqs(
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 23, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('mmseqs'), 'createdb', PosixPath('/public/home/xxx/ras_scan/msas/query.fas'), PosixPath('/public/home/xxx/ras_scan/msas/qdb'), '--shuffle', '0']' died with <Signals.SIGSEGV: 11>.
/public/home/xxx/ras_scan/msas/qdb_h.index.0: No such file or directory
Traceback (most recent call last):
  File "/public/home/xxx/localcolabfold/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 410, in main
    run_mmseqs(
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 23, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/public/home/xxx/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('mmseqs'), 'createdb', PosixPath('/public/home/xxx/ras_scan/msas/query.fas'), PosixPath('/public/home/xxx/ras_scan/msas/qdb'), '--shuffle', '0']' returned non-zero exit status 1.
srun: error: node415: task 20: Exited with exit code 1
srun: Terminating job step 690144.0
slurmstepd: error: *** STEP 690144.0 ON node415 CANCELLED AT 2023-11-12T13:47:38 ***
/public/home/xxx/ras_scan/msas/qdb_h.index.0: No such file or directory
srun: error: node415: tasks 0-18,21-35: Terminated
srun: error: node415: task 19: Exited with exit code 1
srun: Force Terminated job step 690144.0
`

**Comment by AlvinLeopold** [comment]
I solve some trouble about enviroment, and I think the problem occured at

"
Could not delete msas/qdb.0!
Could not copy file msas/qdb_h.0 to msas/qdb_h!
msas/qdb_h.index.0: No such file or directory
msas/qdb_h.index.0: No such file or directory
"
colabfold_search exactly creat the "msas" directory
it contained some files just like above
"qdb  qdb.dbtype  qdb_h  qdb_h.dbtype  qdb_h.index  qdb.index  qdb.lookup  qdb.source  query.fas"

I coud not foud the file like "msas/qdb_h.index.0" nor found any code related to <qdb_h.index.0> in search.py.

Additionally, I'm using the command
`srun colabfold_search \
--db-load-mode 2 \
--mmseqs /public/home/xxx/.conda/envs/MMseq2/bin/mmseqs \
--threads 36 \
--use-env 1 \
--use-templates 1 \
rasras.fasta /public/home/xxx/shared_db/misc/uniref_30 msas`

Any suggestion would be helpful~
Thanks!

**Comment by AlvinLeopold** [comment]
One more thing
My database dectionary contain those files.
"
COLABDB_READY                           colabfold_envdb_202108_seq.tsv  pdb100_230517.7         pdb100_230517_h.9         pdb100_230517.index.10         PDB_MMCIF_READY
colabfold_envdb_202108_aln.tsv          colabfold_envdb_202108.tsv      pdb100_230517.8         pdb100_230517_h.index.0   pdb100_230517.index.11         PDB_READY
colabfold_envdb_202108_db               db_make_688242.err              pdb100_230517.9         pdb100_230517_h.index.1   pdb100_230517.index.12         setup_databases.sh
colabfold_envdb_202108_db_aln           db_make_688242.out              pdb100_230517.fasta.gz  pdb100_230517_h.index.10  pdb100_230517.index.13         tmp1
colabfold_envdb_202108_db_aln.dbtype    dbMake.sh                       pdb100_230517_h.0       pdb100_230517_h.index.11  pdb100_230517.index.14         tmp2
colabfold_envdb_202108_db_aln.index     pdb                             pdb100_230517_h.1       pdb100_230517_h.index.12  pdb100_230517.index.15         uniref30_2302_aln.tsv
colabfold_envdb_202108_db.dbtype        pdb100_230517.0                 pdb100_230517_h.10      pdb100_230517_h.index.13  pdb100_230517.index.16         uniref30_2302_db
colabfold_envdb_202108_db_h             pdb100_230517.1                 pdb100_230517_h.11      pdb100_230517_h.index.14  pdb100_230517.index.17         uniref30_2302_db_aln
colabfold_envdb_202108_db_h.dbtype      pdb100_230517.10                pdb100_230517_h.12      pdb100_230517_h.index.15  pdb100_230517.index.18         uniref30_2302_db_aln.dbtype
colabfold_envdb_202108_db_h.index       pdb100_230517.11                pdb100_230517_h.13      pdb100_230517_h.index.16  pdb100_230517.index.19         uniref30_2302_db_aln.index
colabfold_envdb_202108_db.idx           pdb100_230517.12                pdb100_230517_h.14      pdb100_230517_h.index.17  pdb100_230517.index.2          uniref30_2302_db.dbtype
colabfold_envdb_202108_db.idx.0         pdb100_230517.13                pdb100_230517_h.15      pdb100_230517_h.index.18  pdb100_230517.index.20         uniref30_2302_db_h
colabfold_envdb_202108_db.idx.1         pdb100_230517.14                pdb100_230517_h.16      pdb100_230517_h.index.19  pdb100_230517.index.21         uniref30_2302_db_h.dbtype
colabfold_envdb_202108_db.idx.2         pdb100_230517.15                pdb100_230517_h.17      pdb100_230517_h.index.2   pdb100_230517.index.22         uniref30_2302_db_h.index
colabfold_envdb_202108_db.idx.3         pdb100_230517.16                pdb100_230517_h.18      pdb100_230517_h.index.20  pdb100_230517.index.23         uniref30_2302_db.idx
colabfold_envdb_202108_db.idx.4         pdb100_230517.17                pdb100_230517_h.19      pdb100_230517_h.index.21  pdb100_230517.index.24         uniref30_2302_db.idx.dbtype
colabfold_envdb_202108_db.idx.5         pdb100_230517.18                pdb100_230517_h.2       pdb100_230517_h.index.22  pdb100_230517.index.25         uniref30_2302_db.idx.index
colabfold_envdb_202108_db.idx.6         pdb100_230517.19                pdb100_230517_h.20      pdb100_230517_h.index.23  pdb100_230517.index.26         uniref30_2302_db.idx_mapping
colabfold_envdb_202108_db.idx.7         pdb100_230517.2                 pdb100_230517_h.21      pdb100_230517_h.index.24  pdb100_230517.index.27         uniref30_2302_db.idx_taxonomy
colabfold_envdb_202108_db.idx.index.0   pdb100_230517.20                pdb100_230517_h.22      pdb100_230517_h.index.25  pdb100_230517.index.28         uniref30_2302_db.index
colabfold_envdb_202108_db.idx.index.1   pdb100_230517.21                pdb100_230517_h.23      pdb100_230517_h.index.26  pdb100_230517.index.29         uniref30_2302_db_mapping
colabfold_envdb_202108_db.idx.index.2   pdb100_230517.22                pdb100_230517_h.24      pdb100_230517_h.index.27  pdb100_230517.index.3          uniref30_2302_db_seq
colabfold_envdb_202108_db.idx.index.3   pdb100_230517.23                pdb100_230517_h.25      pdb100_230517_h.index.28  pdb100_230517.index.30         uniref30_2302_db_seq.dbtype
colabfold_envdb_202108_db.idx.index.4   pdb100_230517.24                pdb100_230517_h.26      pdb100_230517_h.index.29  pdb100_230517.index.31         uniref30_2302_db_seq_h
colabfold_envdb_202108_db.idx.index.5   pdb100_230517.25                pdb100_230517_h.27      pdb100_230517_h.index.3   pdb100_230517.index.4          uniref30_2302_db_seq_h.dbtype
colabfold_envdb_202108_db.idx.index.6   pdb100_230517.26                pdb100_230517_h.28      pdb100_230517_h.index.30  pdb100_230517.index.5          uniref30_2302_db_seq_h.index
colabfold_envdb_202108_db.idx.index.7   pdb100_230517.27                pdb100_230517_h.29      pdb100_230517_h.index.31  pdb100_230517.index.6          uniref30_2302_db_seq.index
colabfold_envdb_202108_db.index         pdb100_230517.28                pdb100_230517_h.3       pdb100_230517_h.index.4   pdb100_230517.index.7          uniref30_2302_db_taxonomy
colabfold_envdb_202108_db_seq           pdb100_230517.29                pdb100_230517_h.30      pdb100_230517_h.index.5   pdb100_230517.index.8          uniref30_2302_h.tsv
colabfold_envdb_202108_db_seq.dbtype    pdb100_230517.3                 pdb100_230517_h.31      pdb100_230517_h.index.6   pdb100_230517.index.9          uniref30_2302.md5sum
colabfold_envdb_202108_db_seq_h         pdb100_230517.30                pdb100_230517_h.4       pdb100_230517_h.index.7   pdb100_230517.source           uniref30_2302_seq.tsv
colabfold_envdb_202108_db_seq_h.dbtype  pdb100_230517.31                pdb100_230517_h.5       pdb100_230517_h.index.8   pdb100_a3m.ffdata              uniref30_2302.tsv
colabfold_envdb_202108_db_seq_h.index   pdb100_230517.4                 pdb100_230517_h.6       pdb100_230517_h.index.9   pdb100_a3m.ffindex             UNIREF30_READY
colabfold_envdb_202108_db_seq.index     pdb100_230517.5                 pdb100_230517_h.7       pdb100_230517.index.0     pdb100_foldseek_230517.tar.gz
colabfold_envdb_202108_h.tsv            pdb100_230517.6                 pdb100_230517_h.8       pdb100_230517.index.1     PDB100_READY
"

**Comment by AlvinLeopold** [comment]
when I turn --use-templates to 0
it seems like return some output like 

Converting sequences
createdb msas/query.fas msas/qdb --shuffle 0

MMseqs Version:         14.7e284
Database type           0
Shuffle input database  false
Createdb mode           0
Write lookup file       1
Offset of numeric ids   0
Compressed              0
Verbosity               3

Converting sequences
[=
Create directory msas/tmp
search msas/qdb /public/home/wangxin3303/shared_db/misc/uniref_30/uniref30_2302_db msas/res msas/tmp --threads 36 --num-iterations 3 --db-load-mode 0 -a --k-score 'seq:96,prof:80' -e 0.1 --max-seqs 10000

MMseqs Version:                         14.7e284
Substitution matrix                     aa:blosum62.out,nucl:nucleotide.out
Add backtrace                           true
Alignment mode                          2
Alignment mode                          0
Allow wrapped scoring                   false
E-value threshold                       0.1
Seq. id. threshold                      0
Min alignment length                    0
Seq. id. mode                           0
Alternative alignments                  0
Coverage threshold                      0
Coverage mode                           0
Max sequence length                     65535
Compositional bias                      1
Compositional bias                      1
Max reject                              2147483647
Max accept                              2147483647
Include identical seq. id.              false
Preload mode                            0
Pseudo count a                          substitution:1.100,context:1.400
Pseudo count b                          substitution:4.100,context:5.800
"

But finally it still was canceled, the .err have same output just like before. I'm confused, The RAM cannot support it?

**Comment by milot-mirdita** [comment]
Please post the whole output of the tool, including the error output (stderr). Additionally, if you are using MMseqs2 from Conda, please install the newest release of MMseqs2 (15). This includes a few required features for complex MSAs.

**Comment by AlvinLeopold** [comment]
I tried another version make from git 
<9b9383a3f0c7a99fef37640823174368f74c1487-MPI>

Then try to fix search.py into:
`def run_mmseqs(mmseqs: Path, params: List[Union[str, Path]]):
    params_log = " ".join(str(i) for i in params)
    logger.info(f"Running {mmseqs} {params_log}")
    mpi_cmd = ["mpirun", "-pernode", "-np", "42", mmseqs] + params
    subprocess.check_call(mpi_cmd)`

recieve error
`Can't locate local/lib.pm in @INC (you may need to install the local::lib module) (@INC contains: /public/home/xxx/localcolabfold/colabfold-conda/lib/perl5/5.32/site_perl /public/home/xxx/localcolabfold/colabfold-conda/lib/perl5/site_perl /public/home/xxx/localcolabfold/colabfold-conda/lib/perl5/5.32/vendor_perl /public/home/xxx/localcolabfold/colabfold-conda/lib/perl5/vendor_perl /public/home/xxx/localcolabfold/colabfold-conda/lib/perl5/5.32/core_perl /public/home/xxx/localcolabfold/colabfold-conda/lib/perl5/core_perl .).
BEGIN failed--compilation aborted.
srun: ROUTE: split_hostlist: hl=node[407-410] tree_width 0
[c1342:150704] [[21552,0],0] ORTE_ERROR_LOG: Not found in file ess_hnp_module.c at line 320
[c1341:124141] [[24473,0],0] ORTE_ERROR_LOG: Not found in file ess_hnp_module.c at line 320
[c1337:146627] [[2409,0],0] ORTE_ERROR_LOG: Not found in file ess_hnp_module.c at line 320
[c1338:130468] [[39908,0],0] ORTE_ERROR_LOG: Not found in file ess_hnp_module.c at line 320
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_pmix_base_select failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_pmix_base_select failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
`

**Comment by AlvinLeopold** [comment]
I tried rebuild mmseqs for <git clone> followed instruction. (I think maybe the RAM was ran out)
Now the version showed 9b9383a3f0c7a99fef37640823174368f74c1487-MPI

then I fix the search "search.py" into 
`def run_mmseqs(mmseqs: Path, params: List[Union[str, Path]]):
    params_log = " ".join(str(i) for i in params)
    logger.info(f"Running {mmseqs} {params_log}")
    mpi_cmd = ["mpirun", "-pernode", "-np", "42", mmseqs] + params
    subprocess.check_call(mpi_cmd)
`
The error log:
[test_errorfile.txt](https://github.com/sokrypton/ColabFold/files/13331780/test_errorfile.txt)

**Comment by milot-mirdita** [comment]
Please try without MPI. I don’t think that it will work with colabfold_search. The error indicates that there is some issue with MPI currently.

**Comment by AlvinLeopold** [comment]
It seems ran normal since I reinstall the brand new version of mmseqs.
But the question is that program have kept running for 17 hours, the log file:
[log_14_Nov.txt](https://github.com/sokrypton/ColabFold/files/13343493/log_14_Nov.txt)
Is that normal?

**Comment by milot-mirdita** [comment]
No, it should have provided a lot more output by know (and also finished).

It seems like the database are stored on a network share. Could you try to store them on a local disk, ideally SSD?

The whole `--base` directory (I think by default the current working directory) should not be on a network share.

**Comment by AlvinLeopold** [comment]
Actually I have no choice about ROM, because I'm using HPC so that we have enough RAM to handle this work. The administrator told me that they are using <Distributed File System> as storage system, and the computational node will use the same user to manipulate file. Theoretically the <user> could manipulate the file and the node also can do this.

**Comment by milot-mirdita** [comment]
Do you have the stderr output of the last log you uploaded? There was no actual error in the log.

**Comment by AlvinLeopold** [comment]
The stderr was empty.
the output directory have some files:
qdb  qdb.dbtype  qdb_h  qdb_h.dbtype  qdb_h.index  qdb.index  qdb.lookup  qdb.source  query.fas  tmp

**Comment by milot-mirdita** [comment]
I am running out of ideas then. Can you run an interactive job an your slurm and start the command from within the interactive job? Maybe the log output will be more useful to understand whats going on.

**Comment by AlvinLeopold** [comment]
I'm thinking about that whether the new version mmseqs need rebuild database? The interactive job seems like stock in the read database phase.

**Comment by milot-mirdita** [comment]
No, the databases don't need to be updated. I think the main issue is still that the databases are on a network share.

**Comment by AlvinLeopold** [comment]
If I could use multi-node computing I could keep the database all in RAM, would this not solve the current problem. (I see that there is an MPI option in the output log)

**Comment by AlvinLeopold** [comment]
hi, I tried exporting the memory logs and found that only the AveDiskRead and MaxDiskRead parameters are in the state of growing all the time, does it mean that AveDiskRead reaches a certain threshold value before the calculation starts
[sstat_memory.log](https://github.com/sokrypton/ColabFold/files/13379210/sstat_memory.log)

Cheers and thanks
