### ISSUE TITLE
list index out of range in Display 3D structure

### ISSUE THREAD

**Issue by eirene000** [sokrypton/ColabFold#519]
I put my sequence in query_sequence section and set num_relax as 1. I've customer template mode as 'custom' because I have a similar sequence in 3D structure. 

Everything was going well but I faced 'list index out of range' error in line 12 of Display 3D structure section..What can I do for fixing this error. 

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
I've just launched Alphfold2.ipynb in my MacBook Pro.

**Comment by riquri** [comment]
I encountered a similar error when handling MMCIF files as templates.
In my case, the downloaded files from PDB RCSB caused a UnicodeDecodeError, 
while creating a new text file by copying and pasting in a text editor (VS Code) worked well.

**Comment by milot-mirdita** [comment]
Could you please upload a file that fails? Then we can investigate.

**Comment by bschilder** [comment]
Seems the colabfold team is making changes related to this.
https://github.com/sokrypton/ColabFold/commit/a838b6451306a7bfd9280625f155cd799bbc81f5

@martin-steinegger could you shed some light on this? I tried reinstalling colabfold (via localcolabfold) but no luck so far, very similar error as reported above.

```
(base) [schilder@galaxy1 ENST00000357654]$ colabfold_batch --save-single-representations --save-pair-representations af2_sameMSA/ af2_sameMSA/
2025-08-01 11:28:25,524 Running colabfold 1.5.5 (a838b6451306a7bfd9280625f155cd799bbc81f5)
Traceback (most recent call last):
  File "/home/schilder/projects/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/schilder/projects/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 2030, in main
    queries, is_complex = get_queries(args.input, args.sort_queries_by)
  File "/home/schilder/projects/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/input.py", line 228, in get_queries
    (seqs, header) = parse_fasta(file.read_text())
  File "/home/schilder/projects/localcolabfold/colabfold-conda/lib/python3.10/pathlib.py", line 1135, in read_text
    return f.read()
  File "/home/schilder/projects/localcolabfold/colabfold-conda/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

I can't tell from this output which file is failing, but will keeping looking.

**Comment by bschilder** [comment]
Trying to make a reprex, but so far I cannot replicate the issue from the part that parses the fasta alone:
https://github.com/sokrypton/ColabFold/blob/a838b6451306a7bfd9280625f155cd799bbc81f5/colabfold/input.py#L88
https://github.com/sokrypton/ColabFold/blob/a838b6451306a7bfd9280625f155cd799bbc81f5/colabfold/input.py#L169

The `get_queries` function is called here:
https://github.com/sokrypton/ColabFold/blob/a838b6451306a7bfd9280625f155cd799bbc81f5/colabfold/batch.py#L2028


```py
def parse_fasta(fasta_string: str):
    """Parses FASTA string and returns list of strings with amino-acid sequences.

    Arguments:
      fasta_string: The string contents of a FASTA file.

    Returns:
      A tuple of two lists:
      * A list of sequences.
      * A list of sequence descriptions taken from the comment lines. In the
        same order as the sequences.
    """
    sequences = []
    descriptions = []
    index = -1
    for line in fasta_string.splitlines():
        line = line.strip()
        if line.startswith("#"):
            continue
        if line.startswith(">"):
            index += 1
            descriptions.append(line[1:])  # Remove the '>' at the beginning.
            sequences.append("")
            continue
        elif not line:
            continue  # Skip blank lines.
        sequences[index] += line

    return sequences, descriptions

import pathlib 
haplotype_msas = ['ENSP00000350283_REF.a3m]
for path in haplotype_msas: 
    print(os.path.basename(path))
    input_path = pathlib.Path(path).expanduser()
    msa_string = input_path.read_text()
    sequences, descriptions = parse_fasta(msa_string)
    print(sequences[0])
    print(descriptions[0])
```

Seems to read fine, so the error must be stemming from somewhere else in the code?
```py
ENSP00000350283_REF.a3m
MDLSALRVEEVQNVINAMQKILECPICLELIKEPVSTKCDHIFCKFCMLKLLNQKKGPSQCPLCKNDITKRSLQESTRFSQLVEELLKIICAFQLDTGLEYANSYNFAKKENNSPEHLKDEVSIIQSMGYRNRAKRLLQSEPENPSLQETSLSVQLSNLGTVRTLRTKQRIQPQKTSVYIELGSDSSEDTVNKATYCSVGDQELLQITPQGTRDEISLDSAKKAACEFSETDVTNTEHHQPSNNDLNTTEKRAAERHPEKYQGSSVSNLHVEPCGTNTHASSLQHENSSLLLTKDRMNVEKAEFCNKSKQPGLARSQHNRWAGSKETCNDRRTPSTEKKVDLNADPLCERKEWNKQKLPCSENPRDTEDVPWITLNSSIQKVNEWFSRSDELLGSDDSHDGESESNAKVADVLDVLNEVDEYSGSSEKIDLLASDPHEALICKSERVHSKSVESNIEDKIFGKTYRKKASLPNLSHVTENLIIGAFVTEPQIIQERPLTNKLKRKRRPTSGLHPEDFIKKADLAVQKTPEMINQGTNQTEQNGQVMNITNSGHENKTKGDSIQNEKNPNPIESLEKESAFKTKAEPISSSISNMELELNIHNSKAPKKNRLRRKSSTRHIHALELVVSRNLSPPNCTELQIDSCSSSEEIKKKKYNQMPVRHSRNLQLMEGKEPATGAKKSNKPNEQTSKRHDSDTFPELKLTNAPGSFTKCSNTSELKEFVNPSLPREEKEEKLETVKVSNNAEDPKDLMLSGERVLQTERSVESSSISLVPGTDYGTQESISLLEVSTLGKAKTEPNKCVSQCAAFENPKGLIHGCSKDNRNDTEGFKYPLGHEVNHSRETSIEMEESELDAQYLQNTFKVSKRQSFAPFSNPGNAEEECATFSAHSGSLKKQSPKVTFECEQKEENQGKNESNIKPVQTVNITAGFPVVGQKDKPVDNAKCSIKGGSRFCLSSQFRGNETGLITPNKHGLLQNPYRIPPLFPIKSFVKTKCKKNLLEENFEEHSMSPEREMGNENIPSTVSTISRNNIRENVFKEASSSNINEVGSSTNEVGSSINEIGSSDENIQAELGRNRGPKLNAMLRLGVLQPEVYKQSLPGSNCKHPEIKKQEYEEVVQTVNTDFSPYLISDNLEQPMGSSHASQVCSETPDDLLDDGEIKEDTSFAENDIKESSAVFSKSVQKGELSRSPSPFTHTHLAQGYRRGAKKLESSEENLSSEDEELPCFQHLLFGKVNNIPSQSTRHSTVATECLSKNTEENLLSLKNSLNDCSNQVILAKASQEHHLSEETKCSASLFSSQCSELEDLTANTNTQDPFLIGSSKQMRHQSESQGVGLSDKELVSDDEERGTGLEENNQEEQSMDSNLGEAASGCESETSVSEDCSGLSSQSDILTTQQRDTMQHNLIKLQQEMAELEAVLEQHGSQPSNSYPSIISDSSALEDLRNPEQSTSEKAVLTSQKSSEYPISQNPEGLSADKFEVSADSSTSKNKEPGVERSSPSKCPSLDDRWYMHSCSGSLQNRNYPSQEELIKVVDVEEQQLEESGPHDLTETSYLPRQDLEGTPYLESGISLFSDDPESDPSEDRAPESARVGNIPSSTSALKVPQLKVAESAQSPAAAHTTDTAGYNAMEESVSREKPELTASTERVNKRMSMVVSGLTPEEFMLVYKFARKHHITLTNLITEETTHVVMKTDAEFVCERTLKYFLGIAGGKWVVSYFWVTQSIKERKMLNEHDFEVRGDVVNGRNHQGPKRARESQDRKIFRGLEICCYGPFTNMPTDQLEWMVQLCGASVVKELSSFTLGTGVHPIVVVQPDAWTEDNGFHAIGQMCEAPVVTREWVLDSVALYQCQELDTYLIPQIPHSHY
ENSP00000350283_REF 1000_Genomes_on_GRCh38-Haplosaurus-ENSP00000350283:REF
```


Here's an example a3m file. Just make sure to remove the .txt suffix (had to add that so GH would let me upload the file).

[ENSP00000350283_REF.a3m.txt](https://github.com/user-attachments/files/21551272/ENSP00000350283_REF.a3m.txt)

**Comment by bschilder** [comment]
Ok, so in my case my input is actually a directory `af2_sameMSA/`

This triggers colabfold to search through that directory for any files that contain the target file suffixes:
https://github.com/sokrypton/ColabFold/blob/a838b6451306a7bfd9280625f155cd799bbc81f5/colabfold/input.py#L204

However, I noticed that the `.iterdir()` function is doing something very strange. It's showing these extra hidden files starting with "._" and ending with ".a3m". 

 
```py
input_path = pathlib.Path(os.path.expanduser("~/projects/data/colabfold/ENST00000357654/af2_sameMSA"))
for file in sorted(input_path.iterdir()):
    print(file)
```

<img width="1110" height="431" alt="Image" src="https://github.com/user-attachments/assets/ed05d178-c974-4700-b1ae-356b6a25a394" />


These hidden files seem to contain some nonsense which would be unparsable 

<img width="1112" height="265" alt="Image" src="https://github.com/user-attachments/assets/2b7bdc7d-4c15-4d89-9a75-5a0dad74718a" />

But `get_queries` does not distinguish between these nonsense files and actual a3m files.

So the short term solution is for users manually delete the nonsense files starting in "._".
```
# List the files 
 find . -type f -name "._*"

# Delete the files
 find . -type f -name "._*" -delete
```

<img width="687" height="227" alt="Image" src="https://github.com/user-attachments/assets/7c59cfac-f425-442d-b4e3-929e8dcd0094" />

They longer term solution is for the the colabfold developers modify  `get_queries` so that it checks for these nonsense files and ignore them when iterating over files contains within the input directory.


Another open question is how those files got created in the first place. Not sure if it's on my end, or something within colabfold's code.


**Update**: Deleting the "._" files does indeed get past these errors, but now running into some new ones here: 
- #753
