### ISSUE TITLE
A3M file formatting issue: IndexError: list index out of range

### ISSUE THREAD

**Issue by YousufAKhan** [sokrypton/ColabFold#547]
## Expected Behavior
I am trying to simply upload my own, custom msa, for a simple monomeric protein prediction but I am unable to do so. The first sequence (homo sapiens) is just my query sequence and the rest of the sequences are my a3m alignment

## Current Behavior
This is the error I am receiving 
2024-01-02 03:26:03,420 Running on GPU
2024-01-02 03:26:03,423 Found 2 citations for tools or databases
2024-01-02 03:26:03,423 Query 1/1: test_58ccf_1.custom (length 516)
2024-01-02 03:26:03,427 Could not generate input features test_58ccf_1.custom: list index out of range
Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1482, in run
    = generate_input_feature(query_seqs_unique, query_seqs_cardinality, unpaired_msa, paired_msa,
  File "/content/colabfold/batch.py", line 1009, in generate_input_feature
    feature_dict = build_monomer_feature(
  File "/content/colabfold/batch.py", line 859, in build_monomer_feature
    msa = pipeline.parsers.parse_a3m(unpaired_msa)
  File "/content/alphafold/data/parsers.py", line 173, in parse_a3m
    sequences, descriptions = parse_fasta(a3m_string)
  File "/content/alphafold/data/parsers.py", line 92, in parse_fasta
    sequences[index] += line
IndexError: list index out of range
2024-01-02 03:26:03,427 Done
0

## Steps to Reproduce (for bugs)
I have attached my file
[fs_manual.a3m.zip](https://github.com/sokrypton/ColabFold/files/13806961/fs_manual.a3m.zip)

**Comment by milot-mirdita** [comment]
Can you try to remove the `#A3M#` header and see if it works?

**Comment by MrCTrent** [comment]
I am experiencing the same "list index out of range" error as above, even using the same commands provided.

**Comment by sonaida** [comment]
For me removing the header line (#A3M#) and making 1-line protein sequences solved this problem.

**Comment by YousufAKhan** [comment]
This worked for me if anyone is looking at this thread in the future^

**Comment by YousufAKhan** [comment]
.
