### ISSUE TITLE
docker image for cuda11.1?

### ISSUE THREAD

**Issue by BinhongLiu** [sokrypton/ColabFold#549]
Hi, 
        I found that the available docker images are compatible with the CUDA 11.8 and 12.2, respectively. Would you please build a docker image for cuda 11.1 or 11.2? Many thanks!

**Comment by milot-mirdita** [comment]
Jax only supports CUDA >=11.8, so we can't ship containers with older CUDA.

However, the container comes with all of CUDA already integrated. So you should just be able to use either container and ignore whatever CUDA is already installed on the system.

The only thing that should matter is that the NVIDIA driver is installed. The jax documentation [says](https://jax.readthedocs.io/en/latest/installation.html#nvidia-gpu) the following regarding driver versions:
"We recommend installing the newest driver available from NVIDIA, but the driver must be version >= 525.60.13 for CUDA 12 and >= 450.80.02 for CUDA 11".

I also noticed that I forgot to build new containers for the latest release 1.5.5. I just triggered the build.

**Comment by BinhongLiu** [comment]
Thanks for your prompt reply! 
         That' great, if the docker image for cuda11.8.0 is also compatible with the older CUDA11 versions. My driver version is 460.106.00 so I think it'll work.
Best!

**Comment by BinhongLiu** [comment]
It always failed to establish a new connection when I ran the `python -m colabfold.download`. This might be caused by the network of my server. Is AlphaFold2 Weight the only file that be downloaded? Could I download the file manually? How is the weight file prepared in the cache directory? Thanks.

**Comment by milot-mirdita** [comment]
You can try to start a shell with the container and see if any other command requiring internet works.

Also can you please post the full error message.

**Comment by BinhongLiu** [comment]
error info:

(singularity) [LDLab-hbLiu@gm606-5 colabfold]$ singularity run -B /thinker/glusterfs/home/LDLab-hbLiu/data/colabfold/cache   ~/singularity_images/colabfold_1.5.5-cuda11.8.0.sif   python -m colabfold.download
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (77) bind mounts
Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/cache/colabfold/params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/cache/colabfold'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/colabfold/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/colabfold/download.py", line 139, in <module>
    download_alphafold_params("alphafold2_multimer_v3")
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/colabfold/download.py", line 73, in download_alphafold_params
    params_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: '/cache'
INFO:    Cleaning up image...
(singularity) [LDLab-hbLiu@gm606-5 colabfold]$ singularity run -B /thinker/glusterfs/home/LDLab-hbLiu/data/colabfold/cache:/cache   ~/singularity_images/colabfold_1.5.5-cuda11.8.0.sif   python -m colabfold.download
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (77) bind mounts

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f512dbfdac0>: Failed to establish a new connection: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /alphafold/alphafold_params_colab_2022-12-06.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f512dbfdac0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/colabfold/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/colabfold/download.py", line 139, in <module>
    download_alphafold_params("alphafold2_multimer_v3")
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/colabfold/download.py", line 75, in download_alphafold_params
    response = requests.get(url, stream=True)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /alphafold/alphafold_params_colab_2022-12-06.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f512dbfdac0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
INFO:    Cleaning up image...

**Comment by milot-mirdita** [comment]
You have to mount a writable directory into `/cache`. That's one issue, I am not sure about the connection timeout though.

**Comment by BinhongLiu** [comment]
Just to make sure that the command is right.

the current directory: /thinker/glusterfs/home/LDLab-hbLiu/data/colabfold/
I've checked that the `/thinker/glusterfs/home/LDLab-hbLiu/data/colabfold/cache` directory is writable.

`(singularity) [LDLab-hbLiu@gm606-5 colabfold]$ singularity run -B /thinker/glusterfs/home/LDLab-hbLiu/data/colabfold/cache:/thinker/glusterfs/home/LDLab-hbLiu/cache/   ~/singularity_images/colabfold_1.5.5-cuda11.8.0.sif   python -m colabfold.download`

error: 

INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (77) bind mounts
Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/cache/colabfold/params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/cache/colabfold'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/colabfold/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/colabfold/download.py", line 139, in <module>
    download_alphafold_params("alphafold2_multimer_v3")
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/colabfold/download.py", line 73, in download_alphafold_params
    params_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/envs/colabfold/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: '/cache'
INFO:    Cleaning up image...

**Comment by milot-mirdita** [comment]
The container folder should be /cache not a subfolder

**Comment by BinhongLiu** [comment]
Right. 
I tried with this command:
`(singularity) [LDLab-hbLiu@gm606-5 colabfold]$ singularity run -B /thinker/glusterfs/home/LDLab-hbLiu/data/colabfold/cache:/cache   ~/singularity_images/colabfold_1.5.5-cuda11.8.0.sif   python -m colabfold.download`


error info:
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (77) bind mounts
Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3a2dffbac0>: Failed to establish a new connection: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /alphafold/alphafold_params_colab_2022-12-06.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a2dffbac0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/colabfold/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/colabfold/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/colabfold/download.py", line 139, in <module>
    download_alphafold_params("alphafold2_multimer_v3")
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/colabfold/download.py", line 75, in download_alphafold_params
    response = requests.get(url, stream=True)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/envs/colabfold/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /alphafold/alphafold_params_colab_2022-12-06.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3a2dffbac0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
INFO:    Cleaning up image...

**Comment by milot-mirdita** [comment]
Did you try if another container has internet?

**Comment by BinhongLiu** [comment]
Yes, I checked with other containers and the network is ok. Would it be better for me to download and prepare the files manually?

**Comment by milot-mirdita** [comment]
Can you download the weights archive from a different container?
https://storage.googleapis.com/alphafold/alphafold_params_2021-07-14.tar

**Comment by milot-mirdita** [comment]
Or from outside the container?

**Comment by BinhongLiu** [comment]
I tried on the server but still failed to download the file. But I've downloaded the file on my PC. So the network of my server seems to be the reason. Now should I decompress the `alphafold_params_2021-07-14.tar` file and copy to the `colabfold/params` directory, right?

**Comment by milot-mirdita** [comment]
Its a bit more complicated, we create marker files in the cache directory that the download finished.
See https://github.com/sokrypton/ColabFold/blob/main/colabfold/download.py

You want to download the af2 ptm weights and create an empty `download_finished.txt` file and also the multimer_v3 weights and create an empty `download_complexes_multimer_v3_finished.txt` file. That should work.

**Comment by BinhongLiu** [comment]
Yes! It worked!
By the way, could I feed a prepared msa file into the docker image for the prediction?

**Comment by milot-mirdita** [comment]
Yes, you should be able to use colabfold_batch now as you'd normally do. Just provide an a3m formatted MSA as input.

**Comment by BinhongLiu** [comment]
Here I encounter a new error.

`(singularity) LDLab-hbLiu@node5:~/data/colabfold$ singularity run --nv   -B /thinker/glusterfs/home/LDLab-hbLiu/data/colabfold/cache:/cache -B $(pwd):/work   /thinker/glusterfs/home/LDLab-hbLiu/singularity_images/colabfold_1.5.5-cuda11.8.0.sif   colabfold_batch /work/part_001.a3m /work/output`

error:

INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (77) bind mounts
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (388) bind mounts
2024-01-05 22:44:56,737 Running colabfold 1.5.5
2024-01-05 22:44:57,430 Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter CUDA
2024-01-05 22:44:57,431 Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
2024-01-05 22:44:59,588 Running on GPU
2024-01-05 22:45:00,339 Found 5 citations for tools or databases
2024-01-05 22:45:00,341 Query 1/1: part_001 (length 1045)
2024-01-05 22:46:09,283 Setting max_seq=512, max_extra_seq=5120
warning: Linking two modules of different target triples: 'LLVMDialectModule' is 'nvptx64-nvidia-gpulibs' whereas '' is 'nvptx64-nvidia-cuda'

warning: Linking two modules of different target triples: 'LLVMDialectModule' is 'nvptx64-nvidia-gpulibs' whereas '' is 'nvptx64-nvidia-cuda'

INFO:    Cleaning up image...
Segmentation fault (core dumped)


cuda toolkit: 11.1.0
cuda driver: 460.106.00
I have two Tesla V100 with both 32Gb, and one is in use and occupied 13Gb of memory. And both Tesla were used when run the code, with 510Mb of memory taken from the occupied Tesla and 307Mb of memory taken from the free one. Could this core dumping caused by out of memory? I've tried sequences with shorter length (97 aa) and the error was still there.

**Comment by milot-mirdita** [comment]
Can you try to use the `--disable-unified-memory` parameter for `colabfold_batch`?

**Comment by milot-mirdita** [comment]
I was able to run the 11.8 image on a V100:

```
$ nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-32GB            On | 00000000:1B:00.0 Off |                    0 |
| N/A   36C    P0               24W / 250W|      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

I guess I would recommend trying to update your GPU drivers?

**Comment by BinhongLiu** [comment]
The `--disable-unified-memory` parameter doesn't work. 
I'll try to update the GPU driver.

**Comment by milot-mirdita** [comment]
Did updating the GPU drivers work?

**Comment by BinhongLiu** [comment]
Sorry, I'm still working on it. The GPU server is public and some of my colleagues are using it recently. So I need to find a convenient time for everyone to update the GPU driver.

**Comment by BinhongLiu** [comment]
In addition to updating the GPU driver directly, is there any other way to see if the driver caused the error?

**Comment by BinhongLiu** [comment]
I am grateful for your help. But I have no root permission, and the docker has not been installed on the server so I always run the command through singularity. Anyway, I'll try to figure out whether the GPU driver caused the error.

**Comment by milot-mirdita** [comment]
I mean the part:
`bash -c "apt-get -y update && apt-get -y install gdb && gdb --args python3 -m colabfold.batch /work/seq.fa /work/out"`
should work with singularity as well as docker

**Comment by BinhongLiu** [comment]
my command:
`singularity run --nv -B $(pwd):/cache:rw -B $(pwd):/work:rw /thinker/glusterfs/home/LDLab-hbLiu/singularity_images/colabfold_1.5.5-cuda11.8.0.sif  bash -c "apt-get -y update && apt-get -y install gdb && gdb --args python3 -m colabfold.batch /work/seq.fa /work/out"`

output:
`INFO:    Could not find any nv files on this host!
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (77) bind mounts
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (30: Read-only file system)
INFO:    Cleaning up image...`

**Comment by milot-mirdita** [comment]
Apparently, you can do `--fakeroot --writable` [see here](https://stackoverflow.com/questions/65599721/unable-to-build-writable-singularity-container).

**Comment by BinhongLiu** [comment]
`singularity run --fakeroot --writable -B /thinker/glusterfs/home/LDLab-hbLiu/data/colabfold/cache:/cache:rw \
      -B $(pwd):/work:rw /thinker/glusterfs/home/LDLab-hbLiu/singularity_images/colabfold_1.5.5-cuda11.8.0.sif \
      bash -c "apt-get -y update && apt-get -y install gdb && gdb --args python3 -m colabfold.batch /work/seq.fa /work/out"`


![image](https://github.com/sokrypton/ColabFold/assets/35453307/0f62be04-e9bd-45c9-b2a8-476b1ccf08a8)

**Comment by BinhongLiu** [comment]
`singularity run --fakeroot --writable -B $(pwd):/cache:rw \
>       -B $(pwd):/work:rw /thinker/glusterfs/home/LDLab-hbLiu/singularity_images/colabfold_1.5.5-cuda11.8.0.sif \
>       bash -c "apt-get -y update && apt-get -y install gdb && gdb --args python3 -m colabfold.batch /work/seq.fa /work/out"`

![image](https://github.com/sokrypton/ColabFold/assets/35453307/295e3bfc-785d-450b-8db8-4c2f5ead4639)

**Comment by BinhongLiu** [comment]
`mkdir cache` + `-B cache:/cache` did not work, either.

**Comment by milot-mirdita** [comment]
Sorry, I don't have singularity set-up to test. I guess you can just leave the mounts out, and let it download into the container:

```
singularity run --fakeroot --writable /thinker/glusterfs/home/LDLab-hbLiu/singularity_images/colabfold_1.5.5-cuda11.8.0.sif \
    bash -c "apt-get -y update && apt-get -y install gdb && mkdir /work && (echo -e '>1\nPIAQIHILXEGRSDEQKETLIRE' > /work/seq.fa) && gdb --args python3 -m colabfold.batch /work/seq.fa /work/out"
```

**Comment by BinhongLiu** [comment]
![image](https://github.com/sokrypton/ColabFold/assets/35453307/e57534ba-9303-4943-a33b-47617421a85e)

I've installed the `gdb` but it still could not be found?

**Comment by milot-mirdita** [comment]
Looks good (i think)!

Next, type `r` then Enter. Wait for it to crash, then type `bt` then Enter and copy the output here.

**Comment by BinhongLiu** [comment]
Sorry, the `gdb` could not be found?
![image](https://github.com/sokrypton/ColabFold/assets/35453307/51f3298f-45e1-4e7e-976a-7333bf91a4b7)

**Comment by milot-mirdita** [comment]
Ah, sorry, i didn't see that you called `gdb` outside the container. You are missing the gdb installation commands `apt-get -y update && apt-get -y install gdb`, see my full command above: https://github.com/sokrypton/ColabFold/issues/549#issuecomment-1893998888

**Comment by BinhongLiu** [comment]
I see. It's bad that the GPU node has no network access.
