### ISSUE TITLE
Problem using colabfold_search for complexes

### ISSUE THREAD

**Issue by Nuta0** [sokrypton/ColabFold#553]
## Expected Behavior
Use colabfold_search to generate a msa of a complex.

## Current Behavior
Colabfold_search runs for a while. Then I get an error and no msa is generated.

## Steps to Reproduce (for bugs)
input:
```
module load Miniconda3/22.11.1-1
conda activate /localcolabfold/colabfold-conda
colabfold_search P54025_homodimer.fasta /data/gpfs/datasets/mmseqs/uniref30_2302 msas

```

## ColabFold Output (for bugs)
Error:
```
usage: mmseqs pairaln <i:queryDB> <i:targetDB> <i:alnDB> <o:alnDB> [options]
 By Martin Steinegger <martin.steinegger@snu.ac.kr>
options: common:             
 --db-load-mode INT   Database preload mode 0: auto, 1: fread, 2: mmap, 3: mmap+touch [0]
 --compressed INT     Write compressed output [0]
 --threads INT        Number of CPU-cores used (all by default) [72]
 -v INT               Verbosity level: 0: quiet, 1: +errors, 2: +warnings, 3: +info [3]

references:
 - Steinegger M, Soding J: MMseqs2 enables sensitive protein sequence searching for the analysis of massive data sets. Nature Biotechnology, 35(11), 1026-1028 (2017)
Unrecognized parameter "--pairing-mode". Did you mean "--db-load-mode" (Preload mode)?
Traceback (most recent call last):
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 345, in main
    mmseqs_search_pair(
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 197, in mmseqs_search_pair
    run_mmseqs(mmseqs, ["pairaln", base.joinpath("qdb"), dbbase.joinpath(f"{uniref_db}"), base.joinpath("res_exp_realign"), base.joinpath("res_exp_realign_pair"), "--db-load-mode", str(db_load_mode), "--pairing-mode", str(pairing_strategy), "--pairing-dummy-mode", "0", "--threads", str(threads), ],)
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 25, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('mmseqs'), 'pairaln', PosixPath('msas/qdb'), PosixPath('/data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db'), PosixPath('msas/res_exp_realign'), PosixPath('msas/res_exp_realign_pair'), '--db-load-mode', '0', '--pairing-mode', '0', '--pairing-dummy-mode', '0', '--threads', '64']' returned non-zero exit status 1.
```
## Context
I have installed colabfold using localcolabfold. Version 1.5.2 has worked well previously. I have updated to version 1.5.5 and downloaded the newest version of the mmseqs databases. No I get the above error message. I am able to generate msas for single proteins (eg. MIPIKRSSRRWKKKGRMRWKWYKKRLRRLKRERKRARS), but I get the error when trying to generate msas for complexes (eg. MIPIKRSSRRWKKKGRMRWKWYKKRLRRLKRERKRARS:MIPIKRSSRRWKKKGRMRWKWYKKRLRRLKRERKRARS).

## Your Environment
I am running this on our HPC with 32 CPU cores (Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz) and 250 GB of memory.

**Comment by milot-mirdita** [comment]
Please update mmseqs, the installed version does not support some features that colabfold requires.

**Comment by Nuta0** [comment]
@milot-mirdita Thank you for the quick response. 

The old mmseqs version was MMseqs2/14-7e284. The new one is MMseqs2/15-6f452. 
I ran the following again.
```
module load Miniconda3/22.11.1-1
conda activate /localcolabfold/colabfold-conda
module load MMseqs2/15-6f452
colabfold_search P54025_homodimer.fasta /data/gpfs/datasets/mmseqs/uniref30_2302 msas
```



It looks like the command gets stuck somewhere else now.
This the error I get:
```
pairaln msas/qdb /data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db msas/res_exp_realign msas/res_exp_realign_pair --db-load-mode 0 --pairing-mode 0 --pairing-dummy-mode 0 --threads 64 

MMseqs Version:      	GITDIR-NOTFOUND
Preload mode         	0
Include dummy pairing	0
Pairing mode         	0
Compressed           	0
Threads              	64
Verbosity            	3

/data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db_mapping does not exist. Please create the taxonomy mapping!
Traceback (most recent call last):
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 345, in main
    mmseqs_search_pair(
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 197, in mmseqs_search_pair
    run_mmseqs(mmseqs, ["pairaln", base.joinpath("qdb"), dbbase.joinpath(f"{uniref_db}"), base.joinpath("res_exp_realign"), base.joinpath("res_exp_realign_pair"), "--db-load-mode", str(db_load_mode), "--pairing-mode", str(pairing_strategy), "--pairing-dummy-mode", "0", "--threads", str(threads), ],)
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 25, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/data/gpfs/projects/punim1869/shared_bin/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('mmseqs'), 'pairaln', PosixPath('msas/qdb'), PosixPath('/data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db'), PosixPath('msas/res_exp_realign'), PosixPath('msas/res_exp_realign_pair'), '--db-load-mode', '0', '--pairing-mode', '0', '--pairing-dummy-mode', '0', '--threads', '64']' returned non-zero exit status 1.
```

I have also attached the outputs from this (output_test_2.txt) and the previous run (output_test_1.txt).
I had a quick look in the /data/gpfs/datasets/mmseqs/uniref30_2302/ directory and have attached a screenshot of the contents. The uniref30_2302_db_mapping does seem to exist.

![Screenshot](https://github.com/sokrypton/ColabFold/assets/63578409/a4090c55-c6a9-4ff8-b6ef-c492e7263efd)
[output_test_1.txt](https://github.com/sokrypton/ColabFold/files/13955804/output_test_1.txt)
[output_test_2.txt](https://github.com/sokrypton/ColabFold/files/13955805/output_test_2.txt)

**Comment by milot-mirdita** [comment]
How much RAM does the compute node have where you are running MMseqs2? The error message can also occur if the file cannot be MemoryMapped for some reason.

**Comment by Nuta0** [comment]
I have re-run the script with 768G of RAM (the compute node has 1519GB available) and I get the same error message. I am now thinking that the mmseqs database may not have been setup properly using enough RAM. Could that be the problem?

**Comment by milot-mirdita** [comment]
Can you run the following please?
`head -c 100 /data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db_mapping | xxd`
and
`ls -lah /data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db_mapping`
This is very confusing :(

**Comment by Nuta0** [comment]
I have run those commands. Looks like I don't have permission to read `uniref30_2302_db_mapping `.

```
[ Mon 22 Jan || 16:33 || uniref30_2302 ]> head -c 100 /data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db_mapping | xxd
head: cannot open '/data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db_mapping' for reading: Permission denied
[ Mon 22 Jan || 16:34 || uniref30_2302 ]> ls -lah /data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db_mapping
-rw------- 1 jzhang8 hpcadmin 5.4G May 22  2023 /data/gpfs/datasets/mmseqs/uniref30_2302/uniref30_2302_db_mapping
```

**Comment by milot-mirdita** [comment]
I guess that's the problem

**Comment by Nuta0** [comment]
Yes. This was the problem. 
I have the permission to read the file now and everything is working fine. Thank you for the help. Much appreciated
