### ISSUE TITLE
MsaServer GET/template 400 error for colabfold batch use_templates=True

### ISSUE THREAD

**Issue by teodorpopescuQB** [sokrypton/ColabFold#559]
Hi, 

We have deployed our own MMSEQS2 server on a p4d.24xlarge AWS instance, running the server with all data residing in memory post vmtouch command and using the Alphafold2_batch.ipynb notebook to send requests against our own server.

We want to run search and predictions while including the use of templates (setting[ use_templates=True](https://github.com/sokrypton/ColabFold/blob/a00ce1bcc477491d7693e3816d21ea3fc2cf40fd/colabfold/batch.py#L1232))

## Expected Behavior

Output AF2 predictions

## Current Behavior

Setting use_templates=True in the run function will result in a 400 bad request to the server

###  **Input example**

https://www.rcsb.org/fasta/entry/6MH2

## **Output**

**Server logs**
`
"GET /template/1fve_A,6oge_D,7pkl_L,6bi2_M,3n85_L,7kxj_L,2r8s_L,5bo1_M,1tzi_A,7klg_M,5xhv_Q,6u8k_G,1s78_C,3r1g_L,5e08_L,8dp3_L,5xhg_A,1t3f_A,2qqn_L,4kmt_L HTTP/1.1" 400 5639857
`
**Function output logs**

`
Could not get MSA/templates for rcsb_pdb_6MH2: unexpected end of data
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1453, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 765, in get_msa_and_templates
    a3m_lines_mmseqs2, template_paths = run_mmseqs2(
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/colabfold.py", line 294, in run_mmseqs2
    tar.extractall(path=TMPL_PATH)
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 2264, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 2327, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 2410, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 2463, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 254, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
2024-01-23 14:03:21,105 Done
`

## Steps to Reproduce (for bugs)
- Deploy MMSEQS2 server with 1TB RAM
- Use the Alphafold2_batch.ipynb
- add the fasta file in the input directory
- use the mmcif databases as specified for pdbdivided and pdbobsolete

## Context
- We are using the following databases:
- uniref30_2302_db: as specified in setup_databases.sh
- colabfold_envdb_202108_db:  as specified in setup_databases.sh
- pdb: pdb100_230517  as specified in setup_databases.sh
- pdb70:  [pdb70_from_mmcif_220313.tar.gz](https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb70_from_mmcif_220313.tar.gz)as taken from https://colabfold.mmseqs.com/
- pdbdivided from here : https://files.wwpdb.org/pub/pdb/data/structures/divided/mmCIF/
- pdbobsolete from here: https://files.wwpdb.org/pub/pdb/data/structures/obsolete/mmCIF

## Your Environment
- p4d.24xlarge
- Deployed MMSEQS2 server
- Database loaded into memory with vmtouch

**Comment by milot-mirdita** [comment]
I think the issue is that you need to use the same version (date) for the pdb100 mmseqs and hhblits db (https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb100_foldseek_230517.tar.gz, this one, not the pdb70).

**Comment by milot-mirdita** [comment]
also `colabfold_search` has much lower resource requirements, if you don't need the shortest response times, I would advice against running the server yourself, especially on cloud resources, where RAM is really expensive.

**Comment by teodorpopescuQB** [comment]
Hi @milot-mirdita ,

Thanks a lot for your prompt reply and for the pointers! We have adjusted to use the pdb100 instead of pdb70. Oddly, now the use of templates works for some sequences but not for others

For example:
- [6MH4](https://www.rcsb.org/structure/6MH4) works
- [1DEE](https://www.rcsb.org/structure/1DEE) doesn't work
```

Sharing logs below:

[2024-01-24 11:16:01,399 Query 2/3: 1DEE (length 214)
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:00 remaining: 00:00]
2024-01-24 11:16:03,463 Could not get MSA/templates for 1DEE: unexpected end of data
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1453, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 765, in get_msa_and_templates
    a3m_lines_mmseqs2, template_paths = run_mmseqs2(
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/colabfold.py", line 294, in run_mmseqs2
    tar.extractall(path=TMPL_PATH)
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 2264, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 2327, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 2410, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 2463, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/home/ec2-user/SageMaker/localcolabfold/colabfold-conda/lib/python3.10/tarfile.py", line 254, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
2024-01-24 11:16:03,464 Query 3/3: 6MH4 (length 376)
PENDING:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]
2024-01-24 11:16:03,471 Sleeping for 9s. Reason: PENDING
RUNNING:   6%|▌         | 9/150 [elapsed: 00:09 remaining: 02:21]
2024-01-24 11:16:12,485 Sleeping for 5s. Reason: RUNNING
RUNNING:   9%|▉         | 14/150 [elapsed: 00:14 remaining: 02:16]
2024-01-24 11:16:17,495 Sleeping for 5s. Reason: RUNNING
RUNNING:  13%|█▎        | 19/150 [elapsed: 00:19 remaining: 02:11]
2024-01-24 11:16:22,504 Sleeping for 8s. Reason: RUNNING
RUNNING:  18%|█▊        | 27/150 [elapsed: 00:27 remaining: 02:03]
2024-01-24 11:16:30,516 Sleeping for 10s. Reason: RUNNING
RUNNING:  25%|██▍       | 37/150 [elapsed: 00:37 remaining: 01:53]
2024-01-24 11:16:40,530 Sleeping for 7s. Reason: RUNNING
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:44 remaining: 00:00]
2024-01-24 11:16:55,724 Sequence 0 found templates: ['2egh_B', '1q0q_B', '6mh4_A', '7s04_A']
2024-01-24 11:17:40,194 alphafold2_ptm_model_1_seed_000 recycle=0 pLDDT=95.7 pTM=0.925
2024-01-24 11:17:45,117 alphafold2_ptm_model_1_seed_000 recycle=1 pLDDT=96.1 pTM=0.931 tol=0.393
2024-01-24 11:17:45,118 alphafold2_ptm_model_1_seed_000 took 33.8s (1 recycles)
2024-01-24 11:17:45,261 reranking models by 'plddt' metric
2024-01-24 11:17:45,261 rank_001_alphafold2_ptm_model_1_seed_000 pLDDT=96.1 pTM=0.931
2024-01-24 11:17:45,724 Done
{'rank': [['rank_001_alphafold2_ptm_model_1_seed_000']],
 'metric': [[{'mean_plddt': 96.125,
    'ptm': 0.9306640625,
    'print_line': ' pLDDT=96.1 pTM=0.931'}]]}]
```


Server logs for 1DEE

`
127.0.0.1 - - [24/Jan/2024:11:16:01 +0000] "GET /template/1dee_E,2r8s_L,3n85_L,1hez_C,7kxj_L,7kfw_D,8dp3_L,7kqb_J,7kfy_L,7klg_M,5e08_L,7kfv_G,7kfx_L,6u8k_G,1fve_A,6u8d_L,5d1q_A,6oge_D,7pkl_L,1tzi_A HTTP/1.1" 400 9474577
`

Server logs for 6MH4

`
127.0.0.1 - - [24/Jan/2024:11:16:47 +0000] "GET /template/6mh4_A,6mh4_B,1q0q_B,2egh_B,5kry_B,5kqo_A,1r0k_B,1r0k_D,5kqo_B,3r0i_A,7s04_A,3r0i_B,1k5h_B,1r0l_B,1ono_A,1r0l_D,1r0k_A,1r0k_C,5dul_B,1r0l_C HTTP/1.1" 200 7245203
`

Do you have any debugging recommendations or any further pointers as to what might have gone wrong here?

Thanks in advance for your help!

**Comment by milot-mirdita** [comment]
Can you check if all of these exist somewhere in the either divided or obsolete folder of the PDB rsynced from the PDB mirror:

1dee_E,2r8s_L,3n85_L,1hez_C,7kxj_L,7kfw_D,8dp3_L,7kqb_J,7kfy_L,7klg_M,5e08_L,7kfv_G,7kfx_L,6u8k_G,1fve_A,6u8d_L,5d1q_A,6oge_D,7pkl_L,1tzi_A

**Comment by milot-mirdita** [comment]
Sure, I'd be very happy about a PR. That sounds useful!

**Comment by teodorpopescuQB** [comment]
Hi @milot-mirdita ,

I have now raised a PR here: https://github.com/sokrypton/ColabFold/pull/566

Happy to adjust based on review.

Hope ths helps!
