### ISSUE TITLE
Colabfold_search error with templates to generate pdb-hit file 

### ISSUE THREAD

**Issue by NickWoodall** [sokrypton/ColabFold#560]
## Expected Behavior
Error running local colab_search with templates. Runs normally without templates
output of colabfold_search should be msa and pdb hit files

## Current Behavior

colabfold_search --mmseqs /home/vishubuser/data/colabfold_dbs/MMSeq2_sv/build/bin/mmseqs test_input/monomer_test.fa /home/vishubuser/data/colabfold_dbs/database/ test_output/monomer_single_fa --threads 52 --use-templates 1 --db2 /home/vishubuser/data/colabfold_dbs/database/pdb100_230517

gives error: 
Input /home/vishubuser/data/colabfold_dbs/database/pdb100_230517_seq does not exist
Traceback (most recent call last):
  File "/home/vishubuser/localcolabfold/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/home/vishubuser/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 325, in main
    mmseqs_search_monomer(
  File "/home/vishubuser/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 111, in mmseqs_search_monomer
    run_mmseqs(mmseqs, ["convertalis", base.joinpath("prof_res"), dbbase.joinpath(f"{template_db}{dbSuffix1}"), base.joinpath("res_pdb"),
  File "/home/vishubuser/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 25, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/home/vishubuser/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('/home/vishubuser/data/colabfold_dbs/MMSeq2_sv/build/bin/mmseqs'), 'convertalis', PosixPath('test_output/monomer_single_fa/prof_res'), PosixPath('/home/vishubuser/data/colabfold_dbs/database/pdb100_230517_seq'), PosixPath('test_output/monomer_single_fa/res_pdb'), PosixPath('/home/vishubuser/data/colabfold_dbs/database/pdb100_230517.m8'), '--format-output', 'query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,cigar', '--db-load-mode', '0', '--threads', '52']' returned non-zero exit status 1.

## Your Environment
#current colab database directory generated by setup_databases.sh

COLABDB_READY                                      pdb100_a3m.ffindex
colabfold_envdb_202108_aln.tsv                 pdb100_foldseek_230517.tar.gz
colabfold_envdb_202108_db                       PDB100_READY
colabfold_envdb_202108_db_aln                 PDB_MMCIF_READY
colabfold_envdb_202108_db_aln.dbtype     PDB_READY
colabfold_envdb_202108_db_aln.index        uniref30_2302_aln.tsv
colabfold_envdb_202108_db.dbtype             uniref30_2302_db
colabfold_envdb_202108_db_h                     uniref30_2302_db_aln
colabfold_envdb_202108_db_h.dbtype         uniref30_2302_db_aln.dbtype
colabfold_envdb_202108_db_h.index           uniref30_2302_db_aln.index
colabfold_envdb_202108_db.index               uniref30_2302_db.dbtype
colabfold_envdb_202108_db.m8                   uniref30_2302_db_h
colabfold_envdb_202108_db_seq                 uniref30_2302_db_h.dbtype
colabfold_envdb_202108_db_seq.dbtype     uniref30_2302_db_h.index
colabfold_envdb_202108_db_seq_h             uniref30_2302_db.idx_mapping
colabfold_envdb_202108_db_seq_h.dbtype  uniref30_2302_db.idx_taxonomy
colabfold_envdb_202108_db_seq_h.index    uniref30_2302_db.index
colabfold_envdb_202108_db_seq.index         uniref30_2302_db.m8
colabfold_envdb_202108_h.tsv                        uniref30_2302_db_mapping
colabfold_envdb_202108_seq.tsv                     uniref30_2302_db_seq
colabfold_envdb_202108.tar.gz                     uniref30_2302_db_seq.dbtype
colabfold_envdb_202108.tsv                          uniref30_2302_db_seq_h
pdb                                                               uniref30_2302_db_seq_h.dbtype
pdb100_230517                                           uniref30_2302_db_seq_h.index
pdb100_230517.dbtype                                uniref30_2302_db_seq.index
pdb100_230517.fasta.gz                             uniref30_2302_db_taxonomy
pdb100_230517_h                                      uniref30_2302_h.tsv
pdb100_230517_h.dbtype                            uniref30_2302.md5sum
pdb100_230517_h.index                              uniref30_2302_seq.tsv
pdb100_230517.index                                  uniref30_2302.tar.gz
pdb100_230517.lookup                                 uniref30_2302.tsv
pdb100_230517.source                                UNIREF30_READY
pdb100_a3m.ffdata

Include as many relevant details about the environment you experienced the bug in.

colabfold 1.5.5
using recommended mmseqs version for server msa compatibility; 
MMseqs2-71dd32ec43e3ac4dabf111bbc4b124f1c66a85f1.zip

The databases were setup without creating indices. 
It might be an issue with dbSuffix1 being assigned as "_seq" for the template databases within mmseqs_search_monomer
for non-indexed databases. 
Running the template database as colabfold_envdb_202108_db produces no errors (but no hit file, not unexpected)

Thanks,
Nick Woodall

**Comment by NickWoodall** [comment]
creating indices for the pdb_230517 and hard coding the dbSuffix into search.py for templates results in no errors, but the .m8 file is not written    

if use_templates:
        dbSuffix1 = ".idx"
        dbSuffix2 = ".idx"
        run_mmseqs(mmseqs, ["search", base.joinpath("prof_res"), dbbase.joinpath(template_db), base.joinpath("res_pdb"),
                            base.joinpath("tmp2"), "--db-load-mode", str(db_load_mode), "--threads", str(threads), "-s", "7.5", "-a", "-e", "0.1"])
        run_mmseqs(mmseqs, ["convertalis", base.joinpath("prof_res"), dbbase.joinpath(f"{template_db}{dbSuffix1}"), base.joinpath("res_pdb"),
                            base.joinpath(f"{template_db}.m8"), "--format-output",
                            "query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,cigar",
                            "--db-load-mode", str(db_load_mode), "--threads", str(threads)])
        run_mmseqs(mmseqs, ["rmdb", base.joinpath("res_pdb")])
        dbSuffix1 = "_seq"
        dbSuffix2 = "_aln"

**Comment by NickWoodall** [comment]
15K Jan 25 12:23 pdb100_230517.m8
the .m8 file based on the template_db input was written to the database directory. I suppose I have a fundamental misunderstanding of how this is supposed to work.

**Comment by NickWoodall** [comment]
Thank you for fixing this. Much appreciated.
