### ISSUE TITLE
--prefilter-mode flag incompatible with recommended version of mmseqs (colabfold search)

### ISSUE THREAD

**Issue by NickWoodall** [sokrypton/ColabFold#604]
Input Command:

colabfold_search /home/nwoodall/work/jobs/input_fasta/msa_generation/FACS_cf_run2.csv /data/colabfold_dbs /home/nwoodall/work/jobs/input_fasta/FACS_run2 --db2 pdb100_230517 --use-templates 1 --mmseqs /home/nwoodall/repos/MMseqs2/build/bin/mmseqs

Error Message:

references:
 - Steinegger M, Soding J: MMseqs2 enables sensitive protein sequence searching for the analysis of massive data sets. Nature Biotechnology, 35(11), 1026-1028 (2017)
Unrecognized parameter "--prefilter-mode". Did you mean "--filter-msa" (Filter MSA)?
Traceback (most recent call last):
  File "/home/nwoodall/repos/localcolabfold/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/home/nwoodall/repos/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 390, in main
    mmseqs_search_monomer(
  File "/home/nwoodall/repos/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 101, in mmseqs_search_monomer
    run_mmseqs(mmseqs, ["search", base.joinpath("qdb"), dbbase.joinpath(uniref_db), base.joinpath("res"), base.joinpath("tmp"), "--threads", str(threads)] + search_param)
  File "/home/nwoodall/repos/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/mmseqs/search.py", line 27, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/home/nwoodall/repos/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('/home/nwoodall/repos/MMseqs2/build/bin/mmseqs'), 'search', PosixPath('/home/nwoodall/work/jobs/m_csf1r/input_fasta/FACS_run2/qdb'), PosixPath('/data2/scratch2/nwoodall/colabfold_dbs/uniref30_2302_db'), PosixPath('/home/nwoodall/work/jobs/m_csf1r/input_fasta/FACS_run2/res'), PosixPath('/home/nwoodall/work/jobs/m_csf1r/input_fasta/FACS_run2/tmp'), '--threads', '64', '--num-iterations', '3', '--db-load-mode', '0', '-a', '-e', '0.1', '--max-seqs', '10000', '--prefilter-mode', '2', '--k-score', "'seq:96,prof:80'"]' returned non-zero exit status 1.

This is using the currently recommended version of mmseqs from the github repository. 

Note: [MMseqs2 71dd32ec43e3ac4dabf111bbc4b124f1c66a85f1 (May 28, 2023)](https://github.com/soedinglab/MMseqs2/archive/71dd32ec43e3ac4dabf111bbc4b124f1c66a85f1.zip) is used to create the databases and perform sequece search in the ColabFold MSA server. Please use this version if you want to obtain the same MSAs as the server.

There is no error with the newest version of MMSeqs version.

**Comment by milot-mirdita** [comment]
The message is outdated, please use the latest release. I’ll fix the message at some point.

**Comment by crisdarbellay** [comment]
Hey, I'm encountering the exact same mistake. How can I resolve this? Thank you for your work!

**Comment by milot-mirdita** [comment]
Please use the latest release 15. The recommended version text is outdated.
