### ISSUE TITLE
ColabFold 1.5.5 / AF2 using MMSeqs2 crash due to MMSeqs2 API errors

### ISSUE THREAD

**Issue by jfbazan** [sokrypton/ColabFold#616]
ColabFold stops at the 'Run Prediction' stage with an error message of problems with the MMSeqs2 API. The following error message was generated with the test sequence...where I added an additional G at the end so that it had to make an MSA––the same issue when I was doing a routine run w/ my sequences this afternoon.

Downloading alphafold2_ptm weights to .: 100%|██████████| 3.47G/3.47G [02:01<00:00, 30.6MB/s]
2024-05-02 00:30:50,159 Running on GPU
2024-05-02 00:30:50,162 Found 5 citations for tools or databases
2024-05-02 00:30:50,162 Query 1/1: test3_3bb50 (length 60)
SUBMIT:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]2024-05-02 00:30:50,619 Server didn't reply with json: mkdir /BiO/jobs_loki/MZlARFt15cPcLHFO-iwZw8KfvKnlle37DWi08A: no space left on device

2024-05-02 00:30:50,630 Could not get MSA/templates for test3_3bb50: **MMseqs2 API is giving errors**. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1463, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/content/colabfold/batch.py", line 824, in get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/content/colabfold/colabfold.py", line 209, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2024-05-02 00:30:50,631 Done

The final error message at the bottom is the following. Thx in advance for your expert help in fixing the API issue.

---------------------------------------------------------------------------
**IndexError                                Traceback (most recent call last)
[<ipython-input-34-426f80b9fb32>](https://hksga5jx8mt-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240430-060123_RC00_629368006#) in <cell line: 12>()
     10 show_mainchains = False #@param {type:"boolean"}
     11 
---> 12 tag = results["rank"][0][rank_num - 1]
     13 jobname_prefix = ".custom" if msa_mode == "custom" else ""
     14 pdb_filename = f"{jobname}/{jobname}{jobname_prefix}_unrelaxed_{tag}.pdb"

IndexError: list index out of range**

**Comment by milot-mirdita** [comment]
We were doing some maintenance task earlier today that resulted in a full drive. The issue was fixed shortly after. Sorry about that.
