### ISSUE TITLE
Issue when using template mode

### ISSUE THREAD

**Issue by samuelmurail** [sokrypton/ColabFold#627]
Hello,

I have an issue when using batch.run() locally.
It is running fine but when I am using the template option `pdb100` I have this error:

```
2024-06-05 18:51:24,436 Could not get MSA/templates for Test_1dc59_1: [Errno 2] No such file or directory: 'hhsearch'
Traceback (most recent call last):
  File "/shared/projects/alphafold/murail/conda/env/colabfold_tmp_2/lib/python3.10/site-packages/colabfold/batch.py", line 1453, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/shared/projects/alphafold/murail/conda/env/colabfold_tmp_2/lib/python3.10/site-packages/colabfold/batch.py", line 781, in get_msa_and_templates
    template_feature = mk_template(
  File "/shared/projects/alphafold/murail/conda/env/colabfold_tmp_2/lib/python3.10/site-packages/colabfold/batch.py", line 132, in mk_template
    hhsearch_result = hhsearch_pdb70_runner.query(a3m_lines)
  File "/shared/projects/alphafold/murail/conda/env/colabfold_tmp_2/lib/python3.10/site-packages/alphafold/data/tools/hhsearch.py", line 86, in query
    process = subprocess.Popen(
  File "/shared/projects/alphafold/murail/conda/env/colabfold_tmp_2/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/shared/projects/alphafold/murail/conda/env/colabfold_tmp_2/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hhsearch'
```

And here is my env.yml :

```
name: colabfold-1.5.5
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - colabfold=1.5.5
  - kalign2=2.04
  - hhsuite=3.3.0
  - openmm=7.7.0 
  - pdbfixer
  - jax[cuda11_pip]==0.4.23
  - ipykernel
  - ipywidgets
  - seaborn>=0.11
  - pandas>=1.3.4
  - nglview>=3.0
  - gcc_linux-64
  - pip
  - pip:
    - colabfold_jupyter@git+https://gitlab.rpbs.univ-paris-diderot.fr/rpbs/colabfold_jupyter.git@main
    - tqdm>=4.0
    - pdb_numpy>=0.0.6
    - cmcrameri>=1.7
    - git+https://github.com/samuelmurail/af2_analysis.git@main
```

Any idea how to solve the error ?

The error has also been posted here : https://github.com/sokrypton/ColabFold/issues/409 but as it is quite old I am not sure it should not be reopen.

Cheers,
Samuel

**Comment by milot-mirdita** [comment]
Did you activate the conda environment before calling colabfold? It should find hhsearch in $PATH automatically.

**Comment by samuelmurail** [comment]
Yes of course, as it is working well without template. I'm sot sure it is something dealing with the presence of hhsearch.
hhsearch is present in the conda env.

Could it be linked to pdb100 sequence location ? Where should it be located ?

Cheers,
Samuel

**Comment by milot-mirdita** [comment]
No, the error indicates that hhsearch is not in `$PATH`:

```
No such file or directory: 'hhsearch'
```

Please make sure that the environment is correctly activated and that you can call `hhsearch` directly.

**Comment by samuelmurail** [comment]
Ok I think I understand, where the issue come from.

When I launch jupyter-lab from the conda env it is running fine, the issue come from the fact that were are running the notebook in jupyter-hub.

All python command and import run fine, but subprocess it not launched in the correct conda env.

**Comment by samuelmurail** [comment]
Ok it is fixed:

I add to rewrite the mk_template function to give the good hhsearch location:

```python
from typing import Dict,Any
import colabfold
from alphafold.data import templates, pipeline
from alphafold.data.tools import hhsearch
import sys

def mk_template(
    a3m_lines: str, template_path: str, query_sequence: str
) -> Dict[str, Any]:

    python_path = "/".join(sys.executable.split("/")[:-1])
    template_featurizer = templates.HhsearchHitFeaturizer(
        mmcif_dir=template_path,
        max_template_date="2100-01-01",
        max_hits=20,
        kalign_binary_path=python_path+"/kalign",
        release_dates_path=None,
        obsolete_pdbs_path=None,
    )

    hhsearch_pdb70_runner = hhsearch.HHSearch(
        binary_path=python_path+"/hhsearch", databases=[f"{template_path}/pdb70"]
    )

    hhsearch_result = hhsearch_pdb70_runner.query(a3m_lines)
    hhsearch_hits = pipeline.parsers.parse_hhr(hhsearch_result)
    templates_result = template_featurizer.get_templates(
        query_sequence=query_sequence, hits=hhsearch_hits
    )
    return dict(templates_result.features)

colabfold.batch.mk_template = mk_template
```

**Comment by samuelmurail** [comment]
And in fact we also manage to fix this issue with jupyterhub, by adding the conda/bin PATH to jupyterhub:

here an example, where `XXX/conda/env/NAME/bin` is the location of your conda/bin PATH.

```bash
python -m ipykernel install --user --name colabfold_env --env "PATH" "/opt/conda/condabin:/opt/status_bars/status_bars:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:XXX/conda/env/NAME/bin" 
```

**Comment by samuelmurail** [comment]
I guess we can say it is fixed.
