### ISSUE TITLE
How does not apply MSA server to run ColabFold

### ISSUE THREAD

**Issue by 15019669985** [sokrypton/ColabFold#629]
Hi,I ran this project on my server in order to predict the structure of some polypeptides in batches. Predicting is slow when running on nodes without GPU, and with the parameter set to recycle-3 model-1, each sequence takes about 20 minutes to predict
`colabfold_batch --amber --num-recycle 3 --num-model 1 amps.csv /public/home/shl/alphafold/localcolabfold/colabfold-conda/result`

**However, the nodes on my server with GPU are not connected to the external network (no cable is physically plugged in), so the result of running on 004 node is**

> 2024-06-27 17:03:45,185 Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
2024-06-27 17:03:45,185 Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
2024-06-27 17:03:45,185 Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
2024-06-27 17:03:45,186 Running on GPU
2024-06-27 17:03:47,153 Found 6 citations for tools or databases
2024-06-27 17:03:47,154 Query 1/1544: DRAMP21215 (length 4)
2024-06-27 17:03:47,170 Error while fetching result from MSA server. Retrying... (1/5)                                                                               
2024-06-27 17:03:47,171 Error: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2abedc20f5b0>: Failed to resolve 'api.colabfold.com' ([Errno -2] Name or service not known)"))
2024-06-27 17:03:52,180 Error while fetching result from MSA server. Retrying... (1/5)                                                                               
2024-06-27 17:03:52,181 Error: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2abedc2449d0>: Failed to resolve 'api.colabfold.com' ([Errno -2] Name or service not known)"))
2024-06-27 17:03:57,184 Error while fetching result from MSA server. Retrying... (1/5)                                                                               
2024-06-27 17:03:57,185 Error: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2abedc245270>: Failed to resolve 'api.colabfold.com' ([Errno -2] Name or service not known)"))
2024-06-27 17:04:02,194 Error while fetching result from MSA server. Retrying... (1/5)                                                                               
2024-06-27 17:04:02,195 Error: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2abedc20ff70>: Failed to resolve 'api.colabfold.com' ([Errno -2] Name or service not known)"))
2024-06-27 17:04:07,203 Error while fetching result from MSA server. Retrying... (1/5)                                                                               
2024-06-27 17:04:07,203 Error: HTTPSConnectionPool(host='api.colabfold.com', port=443): Max retries exceeded with url: /ticket/msa (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2abedc245150>: Failed to resolve 'api.colabfold.com' ([Errno -2] Name or service not known)"))
SUBMIT:   0%|                                                                                                                   | 0/150 [elapsed: 00:20 remaining: ?]SUBMIT:   0%|                                                                                                                   | 0/150 [elapsed: 00:23 remaining: ?]
Traceback (most recent call last):
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Looks like can not link to the MSA server**

In fact, the length of the polypeptide sequence that I need to predict is basically no more than 20 amino acids, but the number is more than 1500. Downloading local database takes up a lot of hard disk space.It takes one month to predict on a node with only CPU, may I ask if my project really needs the template of MSA server to help me? 
**What should I do to improve the accuracy and speed of prediction**

**Comment by 15019669985** [comment]
I used this command to avoid the involvement of MSA`colabfold_batch --msa-mode single_sequence --num-recycle 4 --num-model 1 --zip amps_1.csv /public/home/shl/alphafold/localcolabfold/colabfold-conda/result`


> 2024-07-10 15:30:10,307 Running colabfold 1.5.5
2024-07-10 15:30:10,449 Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Host Interpreter CUDA
2024-07-10 15:30:10,450 Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
2024-07-10 15:30:10,450 Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
2024-07-10 15:30:10,450 Running on GPU
2024-07-10 15:30:11,427 Found 2 citations for tools or databases
2024-07-10 15:30:11,428 Query 1/8: DRAMP00766 (length 7)
2024-07-10 15:30:20,849 Padding length to 17
2024-07-10 15:30:21,664 Could not predict DRAMP00766. Not Enough GPU memory? INVALID_ARGUMENT: stream is uninitialized or in an error state
2024-07-10 15:30:21,665 Query 2/8: DRAMP00765 (length 17)
2024-07-10 15:30:23,246 Could not predict DRAMP00765. Not Enough GPU memory? INVALID_ARGUMENT: stream is uninitialized or in an error state
2024-07-10 15:30:23,247 Query 3/8: DRAMP00764 (length 20)
2024-07-10 15:30:24,820 Padding length to 30
2024-07-10 15:30:24,822 Could not predict DRAMP00764. Not Enough GPU memory? INVALID_ARGUMENT: stream is uninitialized or in an error state
2024-07-10 15:30:24,823 Query 4/8: DRAMP00017 (length 24)
2024-07-10 15:30:26,617 Padding length to 30
2024-07-10 15:30:26,619 Could not predict DRAMP00017. Not Enough GPU memory? INVALID_ARGUMENT: stream is uninitialized or in an error state
2024-07-10 15:30:26,619 Query 5/8: DRAMP00385 (length 28)
2024-07-10 15:30:28,128 Padding length to 30
2024-07-10 15:30:28,131 Could not predict DRAMP00385. Not Enough GPU memory? INVALID_ARGUMENT: stream is uninitialized or in an error state
2024-07-10 15:30:28,132 Query 6/8: DRAMP00795 (length 30)
2024-07-10 15:30:29,651 Could not predict DRAMP00795. Not Enough GPU memory? INVALID_ARGUMENT: stream is uninitialized or in an error state
2024-07-10 15:30:29,652 Query 7/8: DRAMP00107 (length 37)
^CTraceback (most recent call last):
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 2033, in main
    run(
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1571, in run
    results = predict_structure(
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 376, in predict_structure
    input_features = model_runner.process_features(feature_dict, random_seed=seed)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/model/model.py", line 103, in process_features
    return features.np_example_to_features(
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/model/features.py", line 93, in np_example_to_features
    tensor_dict = proteins_dataset.np_to_tensor_dict(
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/model/tf/proteins_dataset.py", line 165, in np_to_tensor_dict
    tensor_dict = parse_reshape_logic(tensor_dict, features_metadata)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/model/tf/proteins_dataset.py", line 98, in parse_reshape_logic
    assert_non_empty = tf.assert_greater(
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 992, in assert_greater
    return _binary_assert('>', 'assert_greater', math_ops.greater, np.greater, x,
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 465, in _binary_assert
    y = ops.convert_to_tensor(y, name='y')
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/profiler/trace.py", line 183, in wrapped
    return func(*args, **kwargs)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 713, in convert_to_tensor
    return tensor_conversion_registry.convert(
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 234, in convert
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/constant_tensor_conversion.py", line 29, in _constant_tensor_conversion_function
    return constant_op.constant(v, dtype=dtype, name=name)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/ops/weak_tensor_ops.py", line 142, in wrapper
    return op(*args, **kwargs)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/constant_op.py", line 276, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/constant_op.py", line 291, in _constant_impl
    const_tensor = ops._create_graph_constant(  # pylint: disable=protected-access
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 281, in _create_graph_constant
    const_tensor = g._create_op_internal(  # pylint: disable=protected-access
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 2682, in _create_op_internal
    ret = Operation.from_node_def(
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1177, in from_node_def
    c_op = _create_c_op(g, node_def, inputs, control_input_ops, op_def=op_def)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1042, in _create_c_op
    pywrap_tf_session.TF_SetOpStackTrace(
KeyboardInterrupt
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'assert_sequence_shape_correct_1/Assert/Assert' type=Assert>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 779, in assert_equal
    return _binary_assert('==', 'assert_equal', math_ops.equal, np.equal, x, y,  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
Exception ignored in: <function _TFShouldUseHelper.__del__ at 0x2b5db6ae2f80>
Traceback (most recent call last):
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 89, in __del__
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 80, in _check_sated
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/tensorflow/python/platform/tf_logging.py", line 194, in error
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/logging/__init__.py", line 1506, in error
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/logging/__init__.py", line 1624, in _log
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/logging/__init__.py", line 1634, in handle
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/logging/__init__.py", line 968, in handle
  File "/public/home/shl/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/utils.py", line 39, in emit
ImportError: sys.meta_path is None, Python is likely shutting down


But there's still no way to predict it，The GPU of this server is RTX2080Ti, is it really insufficient GPU memory？

**Comment by milot-mirdita** [comment]
That looks like a very different issue. Please make sure that  the`tensorflow-cpu` package is installed and not `tensorflow`

If you still have issues, please open a new issue and don't reply here.
