### ISSUE TITLE
MMseq2 API error

### ISSUE THREAD

**Issue by GISTAL** [sokrypton/ColabFold#649]
Hi,

I ran into an issue when using the local colabfold API. I tried to produce models for a heterodimer sequence but I encounter a 'MMseq2 API error'.

**Input:**
`colabfold_batch queries predictions --host-url http://localhost --amber --recycle-early-stop-tolerance 0.1 --num-recycle 20 --num-models 3 --rank plddt --use-gpu-relax`

**Input sequences in MULTI-fasta format (one example):**
```
>heterodimer_0-100
RTQEKEQIKTLNNKFASFIDKVRFLEQQNKMLETKWSLLQQQKTARSNMDNMFESYINNLRRQLETLGQEKLKLEAELGNMQGLVEDFKNKYEDEINKRT:
IQNEKETMQSLNDRLASYLDRVRSLETENRRLESKIREHLEKKGPQVRDWSHYFKIIEDLRAQIFANTVDNARIVLQIDNARLAADDFRVKYETELAMRQ
```

**Error:**
```
2024-09-05 12:01:00,416 Could not get MSA/templates for heterodimer_0-100: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/usr/local/xray/conda/colabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1468, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/usr/local/xray/conda/colabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 844, in get_msa_and_templates
    paired_a3m_lines = run_mmseqs2(
  File "/usr/local/xray/conda/colabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/colabfold.py", line 239, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2024-09-05 12:01:00,422 Done
```

I looked into the .a3m files which are produced and found that sequence 1 is correctly indicated as '>101' but sequence 2 is **incorrectly** indicated as '\00>102'. I made some changes into the batch.py and other .py so I would like to know if this is due to me screwing up the .py or if this is a bug.

Kind regards,
Gistal.

**Comment by SivasanjayRaahul** [comment]
I am guessing the api url path is (/ticket/msa) mentioned in the code is different than what the local MMSeqs2-App 
server accepts (/ticket)

**Comment by anishazaveri** [comment]
> I am guessing the api url path (/ticket/msa) mentioned in the code is different than what the local MMSeqs2-App server accepts (/ticket)

How do you solve that?
