### ISSUE TITLE
403 Forbidden message from API

### ISSUE THREAD

**Issue by james-vincent** [sokrypton/ColabFold#658]
We received the following message when running colabfold_batch on a single small test sequence. We get this same result on two different compute clusters. Does this mean our IPs are banned?
Command: colabfold_batch  --num-models 1 --stop-at-score 2 ./6A5J.fasta  ./output

```

SUBMIT:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]
2024-11-04 14:04:16,767 Server didn't reply with json: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

2024-11-04 14:04:16,771 Could not get MSA/templates for 6A5J: MMseqs2 API is giving errors. Please confirm your input is a v
alid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/programs/x86_64-linux/colabfold/1.5.5/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1467, 
in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/programs/x86_64-linux/colabfold/1.5.5/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 827, i
n get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/programs/x86_64-linux/colabfold/1.5.5/colabfold-conda/lib/python3.10/site-packages/colabfold/colabfold.py", line 21
0, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists
, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please tr
y again an hour later.
```

**Comment by milot-mirdita** [comment]
I restricted some IPs due to high load on the MSA servers a few days ago.
Please use the local `colabfold_search` instead of the server if you are making multiple thousands of MSAs per day.

We are still having high load on the server currently, and I will need to further restrict how many jobs can be submitted soon

**Comment by jjv5** [comment]
It would be very helpful to have an error message returned stating this. We spent quite a few man hours trying to figure this out.

**Comment by milot-mirdita** [comment]
There is a prominent warning on every `colabfold_batch` invocation:
```
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can 
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`
```

We are still struggling with high load currently. I will reduce the job token regeneration rate tomorrow to cope with the load.

**Comment by jjv5** [comment]
We appreciate this message and completely understand. We have users submitting jobs from a cluster. The cluster has a single external IP address. If the error message returned from the API just had a little bit extra context we would have known directly what our user issues were. Something like:

403 Forbidden - Your IP address, 123.123.123.123 , has been blocked. Please see .....

That is what would have saved time.
